import { StyleSheet, Platform } from 'react-native';
import { scale, verticalScale, moderateScale } from '@/utils/scale';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#FAFAF9',
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: scale(20),
    marginTop: Platform.OS === 'ios' ? verticalScale(60) : verticalScale(40),
    marginBottom: verticalScale(20),
  },
  backButton: {
    width: scale(48),
    height: scale(48),
    borderRadius: scale(15),
    backgroundColor: '#4CAF50',
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerTitle: {
    flex: 1,
    fontFamily: 'DMSans_500Medium',
    fontSize: moderateScale(18),
    color: '#000000',
    marginLeft: scale(15),
  },
  supportButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: scale(8),
  },
  supportIcon: {
    width: scale(22),
    height: scale(22),
  },
  supportText: {
    fontFamily: 'DMSans_500Medium',
    fontSize: moderateScale(14),
    color: '#4CAF50',
  },
  scrollContent: {
    paddingHorizontal: scale(20),
    paddingBottom: verticalScale(100),
    gap: verticalScale(15),
  },
  statusCard: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#FFFFFF',
    borderWidth: 1.5,
    borderColor: '#4CAF50',
    borderRadius: scale(14),
    padding: scale(16),
  },
  statusTextContainer: {
    flex: 1,
    gap: verticalScale(4),
  },
  statusLabel: {
    fontFamily: 'DMSans_400Regular',
    fontSize: moderateScale(14),
    color: '#898989',
  },
  statusTime: {
    fontFamily: 'DMSans_400Regular',
    fontSize: moderateScale(15),
    color: '#000000',
  },
  statusMessage: {
    fontFamily: 'DMSans_400Regular',
    fontSize: moderateScale(14),
    color: '#898989',
  },
  truckIcon: {
    width: scale(50),
    height: scale(50),
  },
  metaCard: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    backgroundColor: '#FFFFFF',
    borderWidth: 1.5,
    borderColor: '#EBEBEB',
    borderRadius: scale(14),
    padding: scale(16),
  },
  metaBlock: {
    gap: verticalScale(4),
  },
  metaLabel: {
    fontFamily: 'DMSans_400Regular',
    fontSize: moderateScale(14),
    color: '#898989',
  },
  metaValue: {
    fontFamily: 'DMSans_400Regular',
    fontSize: moderateScale(14),
    color: '#000000',
  },
  sectionTitle: {
    fontFamily: 'DMSans_500Medium',
    fontSize: moderateScale(16),
    color: '#000000',
    marginTop: verticalScale(10),
    marginBottom: verticalScale(5),
  },
  detailsCard: {
    backgroundColor: '#FFFFFF',
    borderWidth: 1.5,
    borderColor: '#EBEBEB',
    borderRadius: scale(14),
    padding: scale(16),
  },
  productRow: {
    flexDirection: 'row',
    marginBottom: verticalScale(20),
  },
  productImage: {
    width: scale(100),
    height: scale(100),
    borderRadius: scale(20),
    marginRight: scale(15),
  },
  productInfo: {
    flex: 1,
    justifyContent: 'center',
    gap: verticalScale(4),
  },
  productName: {
    fontFamily: 'DMSans_500Medium',
    fontSize: moderateScale(14),
    color: '#000000',
  },
  productWeight: {
    fontFamily: 'DMSans_500Medium',
    fontSize: moderateScale(14),
    color: '#000000',
    marginBottom: verticalScale(4),
  },
  vendorName: {
    fontFamily: 'DMSans_400Regular',
    fontSize: moderateScale(14),
    color: '#898989',
  },
  locationRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: verticalScale(2),
  },
  locationText: {
    fontFamily: 'DMSans_400Regular',
    fontSize: moderateScale(14),
    color: '#898989',
    marginLeft: scale(4),
  },
  billRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: verticalScale(8),
  },
  billLabel: {
    fontFamily: 'DMSans_400Regular',
    fontSize: moderateScale(14),
    color: '#898989',
  },
  billValue: {
    fontFamily: 'DMSans_400Regular',
    fontSize: moderateScale(14),
    color: '#000000',
  },
  totalRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: verticalScale(8),
    paddingTop: verticalScale(16),
    borderTopWidth: 1.5,
    borderTopColor: '#EBEBEB',
  },
  totalLabel: {
    fontFamily: 'DMSans_500Medium',
    fontSize: moderateScale(14),
    color: '#000000',
  },
  totalValue: {
    fontFamily: 'DMSans_500Medium',
    fontSize: moderateScale(14),
    color: '#4CAF50',
  },
  addressCard: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    backgroundColor: '#FFFFFF',
    borderWidth: 1.5,
    borderColor: '#EBEBEB',
    borderRadius: scale(14),
    padding: scale(16),
    marginBottom: verticalScale(20),
  },
  addressLeft: {
    flexDirection: 'row',
    flex: 1,
    marginRight: scale(10),
  },
  addressIconBlock: {
    marginRight: scale(8),
    marginTop: verticalScale(2),
  },
  addressTextContainer: {
    flex: 1,
    gap: verticalScale(4),
  },
  addressType: {
    fontFamily: 'DMSans_500Medium',
    fontSize: moderateScale(14),
    color: '#000000',
  },
  addressName: {
    fontFamily: 'DMSans_400Regular',
    fontSize: moderateScale(14),
    color: '#404040',
  },
  addressLine: {
    fontFamily: 'DMSans_400Regular',
    fontSize: moderateScale(14),
    color: '#898989',
    lineHeight: moderateScale(19),
  },
  changeButton: {
    backgroundColor: '#4CAF50',
    borderRadius: scale(8),
    paddingVertical: verticalScale(6),
    paddingHorizontal: scale(16),
  },
  changeButtonText: {
    fontFamily: 'DMSans_400Regular',
    fontSize: moderateScale(12),
    color: '#FFFFFF',
    textAlign: 'center',
  },
  actionFooter: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingTop: verticalScale(10),
  },
  trackButton: {
    flex: 1,
    height: verticalScale(50),
    backgroundColor: '#FFFFFF',
    borderWidth: 1.5,
    borderColor: '#4CAF50',
    borderRadius: scale(14),
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: scale(8),
  },
  trackButtonText: {
    fontFamily: 'DMSans_400Regular',
    fontSize: moderateScale(14),
    color: '#000000',
  },
  cancelButton: {
    flex: 1,
    height: verticalScale(50),
    backgroundColor: '#FFFFFF',
    borderWidth: 1.5,
    borderColor: '#E62326',
    borderRadius: scale(14),
    alignItems: 'center',
    justifyContent: 'center',
    marginLeft: scale(8),
  },
  cancelButtonText: {
    fontFamily: 'DMSans_400Regular',
    fontSize: moderateScale(14),
    color: '#E62326',
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.5)',
    justifyContent: 'flex-end',
  },
  modalContent: {
    backgroundColor: '#FFFFFF',
    borderTopLeftRadius: scale(25),
    borderTopRightRadius: scale(25),
    paddingTop: verticalScale(30),
    paddingHorizontal: scale(20),
    paddingBottom: verticalScale(40),
  },
  modalHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: verticalScale(20),
  },
  modalTitle: {
    fontFamily: 'DMSans_500Medium',
    fontSize: moderateScale(16),
    color: '#000000',
    marginLeft: scale(15),
  },
  warningBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(230, 35, 38, 0.2)',
    paddingVertical: verticalScale(10),
    paddingHorizontal: scale(18),
    borderRadius: scale(8),
    marginBottom: verticalScale(16),
  },
  warningIcon: {
    marginRight: scale(10),
  },
  warningText: {
    fontFamily: 'DMSans_400Regular',
    fontSize: moderateScale(14),
    color: '#E62326',
  },
  modalQuestion: {
    fontFamily: 'DMSans_500Medium',
    fontSize: moderateScale(14),
    color: '#000000',
    marginBottom: verticalScale(16),
  },
  radioRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: verticalScale(16),
  },
  radioCircle: {
    width: scale(20),
    height: scale(20),
    borderRadius: scale(10),
    borderWidth: 1.8,
    borderColor: '#4CAF50',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: scale(10),
  },
  radioInnerCircle: {
    width: scale(12),
    height: scale(12),
    borderRadius: scale(6),
    backgroundColor: '#4CAF50',
  },
  radioText: {
    fontFamily: 'DMSans_400Regular',
    fontSize: moderateScale(14),
    color: '#000000',
  },
  reasonLabel: {
    fontFamily: 'DMSans_400Regular',
    fontSize: moderateScale(14),
    color: '#898989',
    marginBottom: verticalScale(10),
  },
  reasonInput: {
    borderWidth: 1.5,
    borderColor: '#EBEBEB',
    borderRadius: scale(14),
    padding: scale(14),
    height: verticalScale(100),
    fontFamily: 'DMSans_400Regular',
    fontSize: moderateScale(14),
    color: '#000000',
    textAlignVertical: 'top',
    marginBottom: verticalScale(20),
  },
  modalFooter: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  goBackButton: {
    flex: 1,
    height: verticalScale(50),
    backgroundColor: '#FFFFFF',
    borderWidth: 1.5,
    borderColor: '#4CAF50',
    borderRadius: scale(14),
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: scale(6),
  },
  goBackButtonText: {
    fontFamily: 'DMSans_500Medium',
    fontSize: moderateScale(15),
    color: '#000000',
  },
  confirmCancelButton: {
    flex: 1,
    height: verticalScale(50),
    backgroundColor: '#E62326',
    borderRadius: scale(14),
    alignItems: 'center',
    justifyContent: 'center',
    marginLeft: scale(6),
  },
  confirmCancelButtonText: {
    fontFamily: 'DMSans_500Medium',
    fontSize: moderateScale(15),
    color: '#FFFFFF',
  },
  ratingCard: {
    backgroundColor: '#FFFFFF',
    borderWidth: 1.8,
    borderColor: '#EBEBEB',
    borderRadius: scale(14),
    paddingVertical: verticalScale(18),
    paddingHorizontal: scale(16),
    gap: verticalScale(15),
    marginBottom: verticalScale(20),
  },
  ratingHeader: {
    gap: verticalScale(10),
  },
  ratingTitle: {
    fontFamily: 'DMSans_400Regular',
    fontSize: moderateScale(14),
    color: '#000000',
  },
  ratingSubtitle: {
    fontFamily: 'DMSans_400Regular',
    fontSize: moderateScale(14),
    color: '#898989',
  },
  starsContainer: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    gap: scale(9),
  },
  feedbackContainer: {
    gap: verticalScale(10),
  },
  feedbackLabel: {
    fontFamily: 'DMSans_400Regular',
    fontSize: moderateScale(14),
    color: '#898989',
  },
  feedbackInput: {
    borderWidth: 1.5,
    borderColor: '#EBEBEB',
    borderRadius: scale(14),
    padding: scale(14),
    height: verticalScale(101),
    fontFamily: 'DMSans_400Regular',
    fontSize: moderateScale(14),
    color: '#898989',
    textAlignVertical: 'top',
  },
  submitRatingButton: {
    borderWidth: 1.5,
    borderColor: '#4CAF50',
    borderRadius: scale(14),
    paddingVertical: verticalScale(12),
    alignItems: 'center',
    justifyContent: 'center',
  },
  submitRatingText: {
    fontFamily: 'DMSans_400Regular',
    fontSize: moderateScale(14),
    color: '#000000',
  },
  buyAgainButton: {
    flex: 1,
    height: verticalScale(50),
    backgroundColor: '#FFFFFF',
    borderWidth: 2,
    borderColor: '#4CAF50',
    borderRadius: scale(14),
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: scale(8),
  },
  buyAgainButtonText: {
    fontFamily: 'DMSans_500Medium',
    fontSize: moderateScale(17),
    color: '#000000',
  },
  viewInvoiceButton: {
    flex: 1,
    height: verticalScale(50),
    backgroundColor: '#4CAF50',
    borderRadius: scale(14),
    alignItems: 'center',
    justifyContent: 'center',
    marginLeft: scale(8),
  },
  viewInvoiceButtonText: {
    fontFamily: 'DMSans_500Medium',
    fontSize: moderateScale(16),
    color: '#FFFFFF',
  },
  viewInvoiceHollowButton: {
    height: verticalScale(50),
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#4CAF50',
    borderRadius: scale(14),
    alignItems: 'center',
    justifyContent: 'center',
    width: '100%',
  },
  viewInvoiceHollowButtonText: {
    fontFamily: 'DMSans_500Medium',
    fontSize: moderateScale(16),
    color: '#000000',
  }
});
