import { StyleSheet } from 'react-native';
import { s, vs, ms } from '@/utils/scale';

export const cartStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#FAFAF9',
  },
  headerContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: s(20),
    paddingTop: vs(30),
    paddingBottom: vs(15),
    gap: s(16),
  },
  backButton: {
    width: s(48),
    height: s(48),
    backgroundColor: '#4CAF50',
    borderRadius: s(15),
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerTitle: {
    fontFamily: 'Poppins_500Medium',
    fontSize: ms(18),
    color: '#000000',
  },
  scrollContent: {
    paddingHorizontal: s(20),
    paddingBottom: vs(120),
    gap: vs(16),
  },
  selectionRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: s(16),
    height: vs(48),
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#EBEBEB',
    borderRadius: s(14),
    marginBottom: vs(8),
  },
  selectionLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: s(12),
  },
  selectionText: {
    fontFamily: 'DMSans_400Regular',
    fontSize: ms(14),
    color: '#000000',
  },
  deleteBtn: {
    width: s(27),
    height: s(28),
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#4CAF50',
    borderRadius: s(6),
    alignItems: 'center',
    justifyContent: 'center',
  },
  cartItemCard: {
    flexDirection: 'row',
    alignItems: 'center',
    width: '100%',
    height: vs(151),
  },
  itemImageWrapper: {
    width: s(132),
    height: vs(151),
    borderTopLeftRadius: s(14),
    borderBottomLeftRadius: s(14),
    overflow: 'hidden',
    backgroundColor: '#FFFFFF',
    borderWidth: 1.5,
    borderRightWidth: 0,
    borderColor: '#EBEBEB',
  },
  itemImage: {
    width: '100%',
    height: '100%',
  },
  checkboxOverlay: {
    position: 'absolute',
    top: vs(10),
    left: s(10),
    width: s(26),
    height: s(26),
    backgroundColor: '#FFFFFF',
    borderRadius: s(6),
    alignItems: 'center',
    justifyContent: 'center',
  },
  itemInfo: {
    flex: 1,
    height: vs(151),
    backgroundColor: '#FFFFFF',
    borderWidth: 1.5,
    borderLeftWidth: 0,
    borderColor: '#EBEBEB',
    borderTopRightRadius: s(14),
    borderBottomRightRadius: s(14),
    padding: s(14),
    flexDirection: 'column',
    alignItems: 'flex-start',
    gap: vs(4),
  },
  topBlock: {
    flexDirection: 'column',
    width: '100%',
    gap: vs(4),
  },
  nameRatingRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  productName: {
    fontFamily: 'DMSans_500Medium',
    fontSize: ms(14),
    color: '#000000',
  },
  ratingRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: s(2),
  },
  ratingText: {
    fontFamily: 'DMSans_400Regular',
    fontSize: ms(14),
    color: '#898989',
  },
  sellerBlock: {
    flexDirection: 'column',
    gap: vs(1),
  },
  sellerName: {
    fontFamily: 'DMSans_400Regular',
    fontSize: ms(14),
    color: '#898989',
  },
  locationRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: s(2),
  },
  locationText: {
    fontFamily: 'DMSans_400Regular',
    fontSize: ms(14),
    color: '#898989',
  },
  priceQtyBlock: {
    flexDirection: 'column',
    gap: vs(6),
    marginTop: vs(4),
  },
  priceRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  priceSymbol: {
    fontFamily: 'DMSans_700Bold',
    fontSize: ms(18),
    color: '#4CAF50',
  },
  priceValue: {
    fontFamily: 'DMSans_700Bold',
    fontSize: ms(18),
    color: '#4CAF50',
  },
  qtyRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: s(20),
  },
  qtyBtn: {
    width: s(25),
    height: s(25),
    backgroundColor: '#4CAF50',
    borderRadius: s(6),
    alignItems: 'center',
    justifyContent: 'center',
  },
  qtyText: {
    fontFamily: 'DMSans_400Regular',
    fontSize: ms(14),
    color: '#000000',
  },
  priceDetailsContainer: {
    marginTop: vs(16),
    flexDirection: 'column',
    gap: vs(8),
  },
  priceDetailsTitle: {
    fontFamily: 'DMSans_500Medium',
    fontSize: ms(16),
    color: '#000000',
  },
  priceDetailsBox: {
    flexDirection: 'column',
    padding: s(16),
    gap: vs(8),
    backgroundColor: '#FFFFFF',
    borderWidth: 1.5,
    borderColor: '#EBEBEB',
    borderRadius: s(14),
  },
  priceLine: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  priceLabel: {
    fontFamily: 'DMSans_400Regular',
    fontSize: ms(14),
    color: '#898989',
  },
  priceLineValue: {
    fontFamily: 'DMSans_400Regular',
    fontSize: ms(14),
    color: '#000000',
  },
  totalAmountBox: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: s(16),
    height: vs(50),
    backgroundColor: '#FFFFFF',
    borderWidth: 1.5,
    borderColor: '#EBEBEB',
    borderRadius: s(14),
    marginTop: vs(8),
  },
  totalAmountLabel: {
    fontFamily: 'DMSans_500Medium',
    fontSize: ms(14),
    color: '#000000',
  },
  totalAmountValue: {
    fontFamily: 'DMSans_500Medium',
    fontSize: ms(14),
    color: '#000000',
  },
  checkoutContainer: {
    position: 'absolute',
    bottom: vs(30),
    left: s(20),
    right: s(20),
  },
  checkoutBtn: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    height: vs(50),
    backgroundColor: '#4CAF50',
    borderRadius: s(14),
    shadowColor: '#4CAF50',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.12,
    shadowRadius: 4,
    elevation: 2,
  },
  checkoutText: {
    fontFamily: 'DMSans_500Medium',
    fontSize: ms(15),
    color: '#FFFFFF',
  },
});
