import { StyleSheet } from 'react-native';
import { s, vs, ms } from '@/utils/scale';

export const productStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#FAFAF9',
  },
  headerContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: s(20),
    paddingTop: vs(30),
    paddingBottom: vs(12),
    gap: s(10),
  },
  backButton: {
    width: s(48),
    height: s(48),
    backgroundColor: '#4CAF50',
    borderRadius: s(15),
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerTitle: {
    fontFamily: 'Poppins_500Medium',
    fontSize: ms(18),
    lineHeight: ms(27),
    color: '#000000',
  },
  searchRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: s(20),
    marginBottom: vs(12),
    gap: s(10),
  },
  searchContainer: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: s(14),
    gap: s(10),
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#EBEBEB',
    borderRadius: s(14),
    height: vs(48),
  },
  searchInput: {
    fontFamily: 'DMSans_400Regular',
    fontSize: ms(14),
    color: '#000000',
    flex: 1,
  },
  filterButton: {
    width: s(48),
    height: s(48),
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#EBEBEB',
    borderRadius: s(14),
    alignItems: 'center',
    justifyContent: 'center',
  },
  productsScroll: {
    paddingHorizontal: s(20),
    paddingBottom: vs(40),
  },
  productCard: {
    flexDirection: 'row',
    alignItems: 'center',
    width: '100%',
    height: vs(146),
    marginBottom: vs(12),
  },
  productImage: {
    width: s(132),
    height: vs(146),
    borderTopLeftRadius: s(14),
    borderBottomLeftRadius: s(14),
    backgroundColor: '#FFFFFF',
    borderWidth: 1.5,
    borderRightWidth: 0,
    borderColor: '#EBEBEB',
  },
  productInfo: {
    flex: 1,
    height: vs(146),
    backgroundColor: '#FFFFFF',
    borderWidth: 1.5,
    borderLeftWidth: 0,
    borderColor: '#EBEBEB',
    borderTopRightRadius: s(14),
    borderBottomRightRadius: s(14),
    padding: s(14),
    gap: vs(10),
    flexDirection: 'column',
    alignItems: 'flex-start',
  },
  topBlock: {
    flexDirection: 'column',
    alignItems: 'flex-start',
    gap: vs(4),
    width: '100%',
  },
  nameRatingRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    width: '100%',
  },
  productName: {
    fontFamily: 'DMSans_500Medium',
    fontSize: ms(14),
    lineHeight: ms(20),
    color: '#000000',
  },
  ratingRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: s(2),
  },
  ratingText: {
    fontFamily: 'DMSans_400Regular',
    fontSize: ms(14),
    lineHeight: ms(18),
    color: '#898989',
  },
  sellerLocationBlock: {
    flexDirection: 'column',
    alignItems: 'flex-start',
    gap: vs(1),
  },
  sellerName: {
    fontFamily: 'DMSans_400Regular',
    fontSize: ms(14),
    lineHeight: ms(20),
    color: '#898989',
  },
  locationText: {
    fontFamily: 'DMSans_400Regular',
    fontSize: ms(14),
    lineHeight: ms(20),
    color: '#898989',
  },
  distanceRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: s(2),
  },
  distanceText: {
    fontFamily: 'DMSans_400Regular',
    fontSize: ms(14),
    lineHeight: ms(18),
    color: '#898989',
  },
  priceRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: s(2),
  },
  priceSymbol: {
    fontFamily: 'DMSans_700Bold',
    fontSize: ms(18),
    color: '#4CAF50',
  },
  priceValue: {
    fontFamily: 'DMSans_700Bold',
    fontSize: ms(18),
    color: '#4CAF50',
  },
  priceUnit: {
    fontFamily: 'DMSans_400Regular',
    fontSize: ms(18),
    color: '#000000',
  },
});
