import { StyleSheet } from 'react-native';
import { s, vs, ms } from '@/utils/scale';

export const detailsStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#FAFAF9',
  },
  carouselContainer: {
    flexDirection: 'column',
    alignItems: 'center',
    gap: vs(10),
    width: '100%',
    height: vs(347),
  },
  carouselImage: {
    width: '100%',
    height: vs(330),
  },
  paginationRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: s(10),
  },
  dotActive: {
    width: s(7),
    height: s(7),
    backgroundColor: '#4CAF50',
    borderRadius: s(4),
  },
  dotInactive: {
    width: s(7),
    height: s(7),
    backgroundColor: '#D9D9D9',
    borderRadius: s(4),
  },
  backButton: {
    position: 'absolute',
    left: s(20),
    top: vs(30),
    width: s(48),
    height: s(48),
    backgroundColor: '#4CAF50',
    borderRadius: s(15),
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 10,
  },
  shareButton: {
    position: 'absolute',
    right: s(20),
    top: vs(30),
    width: s(48),
    height: s(48),
    backgroundColor: '#4CAF50',
    borderRadius: s(15),
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 10,
  },
  scrollContent: {
    paddingHorizontal: s(20),
    paddingTop: vs(15),
    paddingBottom: vs(100),
    gap: vs(15),
  },
  sectionBlock: {
    flexDirection: 'column',
    alignItems: 'flex-start',
    gap: vs(8),
    width: '100%',
  },
  sectionTitle: {
    fontFamily: 'DMSans_500Medium',
    fontSize: ms(16),
    lineHeight: ms(20),
    color: '#000000',
  },
  infoBox: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    padding: s(16),
    width: '100%',
    backgroundColor: '#FFFFFF',
    borderWidth: 1.5,
    borderColor: '#EBEBEB',
    borderRadius: s(14),
  },
  titleCol: {
    flexDirection: 'column',
    alignItems: 'flex-start',
    gap: vs(2),
  },
  productName: {
    fontFamily: 'DMSans_400Regular',
    fontSize: ms(16),
    lineHeight: ms(20),
    color: '#000000',
  },
  priceRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  priceSymbol: {
    fontFamily: 'DMSans_700Bold',
    fontSize: ms(20),
    lineHeight: ms(26),
    color: '#4CAF50',
  },
  priceValue: {
    fontFamily: 'DMSans_700Bold',
    fontSize: ms(20),
    lineHeight: ms(26),
    color: '#4CAF50',
  },
  priceUnit: {
    fontFamily: 'DMSans_400Regular',
    fontSize: ms(20),
    lineHeight: ms(26),
    color: '#000000',
  },
  ratingCol: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: s(3),
  },
  ratingText: {
    fontFamily: 'DMSans_400Regular',
    fontSize: ms(14),
    lineHeight: ms(18),
    color: '#898989',
  },
  sellerBox: {
    flexDirection: 'column',
    alignItems: 'flex-start',
    padding: s(16),
    gap: vs(6),
    width: '100%',
    backgroundColor: '#FFFFFF',
    borderWidth: 1.5,
    borderColor: '#EBEBEB',
    borderRadius: s(14),
  },
  sellerName: {
    fontFamily: 'DMSans_400Regular',
    fontSize: ms(14),
    lineHeight: ms(20),
    color: '#000000',
  },
  locationRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: s(8),
  },
  sellerLocationText: {
    fontFamily: 'DMSans_400Regular',
    fontSize: ms(14),
    lineHeight: ms(20),
    color: '#000000',
  },
  distanceRowInner: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: s(2),
  },
  verifiedRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: s(6),
  },
  verifiedText: {
    fontFamily: 'DMSans_400Regular',
    fontSize: ms(14),
    lineHeight: ms(20),
    color: '#4CAF50',
  },
  detailsBox: {
    flexDirection: 'column',
    alignItems: 'flex-start',
    padding: s(16),
    gap: vs(6),
    width: '100%',
    backgroundColor: '#FFFFFF',
    borderWidth: 1.5,
    borderColor: '#EBEBEB',
    borderRadius: s(14),
  },
  detailText: {
    fontFamily: 'DMSans_400Regular',
    fontSize: ms(14),
    lineHeight: ms(20),
    color: '#898989',
  },
  reviewsHeaderRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    width: '100%',
  },
  seeAllText: {
    fontFamily: 'DMSans_400Regular',
    fontSize: ms(14),
    lineHeight: ms(20),
    color: '#000000',
  },
  reviewsScroll: {
    gap: s(12),
    paddingRight: s(20),
  },
  reviewCard: {
    flexDirection: 'column',
    alignItems: 'flex-start',
    padding: s(14),
    gap: vs(10),
    width: s(344),
    height: vs(131),
    backgroundColor: '#FFFFFF',
    borderWidth: 1.5,
    borderColor: '#EBEBEB',
    borderRadius: s(14),
  },
  reviewTopRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    width: '100%',
  },
  reviewerInfoCol: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: s(12),
  },
  avatar: {
    width: s(40),
    height: s(40),
    backgroundColor: '#4CAF50',
    borderRadius: s(20),
    alignItems: 'center',
    justifyContent: 'center',
  },
  avatarText: {
    fontFamily: 'DMSans_500Medium',
    fontSize: ms(19),
    color: '#FFFFFF',
  },
  reviewerNameCol: {
    flexDirection: 'column',
    alignItems: 'flex-start',
    gap: vs(6),
  },
  reviewerName: {
    fontFamily: 'DMSans_500Medium',
    fontSize: ms(16),
    lineHeight: ms(21),
    color: '#000000',
  },
  starsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: s(8),
  },
  reviewDate: {
    fontFamily: 'DMSans_400Regular',
    fontSize: ms(14),
    lineHeight: ms(22),
    color: '#898989',
  },
  reviewText: {
    fontFamily: 'DMSans_400Regular',
    fontSize: ms(14),
    lineHeight: ms(22),
    color: '#898989',
    width: '100%',
  },
  qtyBox: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: s(16),
    width: '100%',
    backgroundColor: '#FFFFFF',
    borderWidth: 1.5,
    borderColor: '#EBEBEB',
    borderRadius: s(14),
  },
  qtyBtn: {
    width: s(40),
    height: s(40),
    backgroundColor: '#4CAF50',
    borderRadius: s(8),
    alignItems: 'center',
    justifyContent: 'center',
  },
  qtyText: {
    fontFamily: 'DMSans_500Medium',
    fontSize: ms(16),
    lineHeight: ms(20),
    color: '#000000',
  },
  noteText: {
    fontFamily: 'DMSans_400Regular',
    fontSize: ms(14),
    lineHeight: ms(20),
    color: '#000000',
    marginTop: vs(8),
  },
  footerContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: s(20),
    paddingVertical: vs(14),
    backgroundColor: '#FAFAF9',
    position: 'absolute',
    bottom: vs(30),
    left: 0,
    right: 0,
    gap: s(12),
  },
  addToCartBtn: {
    flex: 1,
    height: vs(50),
    backgroundColor: '#FFFFFF',
    borderWidth: 2,
    borderColor: '#4CAF50',
    borderRadius: s(14),
    alignItems: 'center',
    justifyContent: 'center',
  },
  addToCartText: {
    fontFamily: 'DMSans_500Medium',
    fontSize: ms(15),
    color: '#000000',
  },
  buyNowBtn: {
    flex: 1,
    height: vs(50),
    backgroundColor: '#4CAF50',
    borderRadius: s(14),
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#4CAF50',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.12,
    shadowRadius: 4,
    elevation: 2,
  },
  buyNowText: {
    fontFamily: 'DMSans_500Medium',
    fontSize: ms(15),
    color: '#FFFFFF',
  },
});
