import { StyleSheet, Platform } from 'react-native';
import { s, vs, ms } from '@/utils/scale';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#FAFAF9',
  },
  headerContainer: {
    paddingHorizontal: s(20),
    paddingTop: Platform.OS === 'ios' ? vs(60) : vs(40),
    paddingBottom: vs(10),
  },
  locationRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  locationInfo: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
  locationIconContainer: {
    width: s(24),
    height: s(24),
    borderRadius: s(12),
    backgroundColor: '#D9D9D9',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: s(8),
  },
  locationTextContainer: {
    flexDirection: 'column',
  },
  deliverToText: {
    fontFamily: 'Poppins_400Regular',
    fontSize: ms(14),
    lineHeight: ms(21),
    color: '#5D5D5D',
  },
  cityText: {
    fontFamily: 'Poppins_500Medium',
    fontSize: ms(16),
    lineHeight: ms(24),
    color: '#000000',
  },
  bellIconContainer: {
    width: s(45),
    height: s(45),
    borderRadius: s(14),
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#EBEBEB',
  },
  searchContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderRadius: s(14),
    paddingHorizontal: s(14),
    height: vs(50),
    marginHorizontal: s(20),
    borderWidth: 1,
    borderColor: '#EBEBEB',
  },
  searchInput: {
    flex: 1,
    marginLeft: s(10),
    fontFamily: 'DMSans_400Regular',
    fontSize: ms(14),
    lineHeight: ms(18),
    color: '#898989',
  },
  bannerContainer: {
    marginHorizontal: s(20),
    marginTop: vs(20),
    borderRadius: s(14),
    backgroundColor: '#4CAF50',
    overflow: 'hidden',
    height: vs(160),
  },
  bannerContent: {
    padding: s(18),
    flex: 1,
    justifyContent: 'space-between',
    zIndex: 1,
  },
  bannerTitle: {
    fontFamily: 'DMSans_500Medium',
    fontSize: ms(24),
    lineHeight: ms(30),
    color: '#FFFFFF',
    width: s(197),
  },
  bannerSubtitle: {
    fontFamily: 'DMSans_500Medium',
    fontSize: ms(16),
    lineHeight: ms(24),
    color: '#F4F4F4',
    marginTop: vs(10),
    width: s(166),
  },
  bannerImage: {
    position: 'absolute',
    right: 0,
    top: vs(10),
    width: s(150),
    height: s(150),
  },
  sectionContainer: {
    marginTop: vs(25),
  },
  sectionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: s(20),
    marginBottom: vs(12),
  },
  sectionTitle: {
    fontFamily: 'DMSans_500Medium',
    fontSize: ms(16),
    lineHeight: ms(30),
    color: '#000000',
  },
  seeAllText: {
    fontFamily: 'DMSans_400Regular',
    fontSize: ms(14),
    lineHeight: ms(18),
    color: '#000000',
  },
  categoriesScroll: {
    paddingLeft: s(20),
    paddingRight: s(10),
  },
  categoryCard: {
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#FFFFFF',
    borderRadius: s(14),
    borderWidth: 1.5,
    borderColor: '#EBEBEB',
    paddingHorizontal: s(8),
    marginRight: s(10),
    width: s(112),
    height: s(112),
  },
  categoryImage: {
    width: '80%',
    height: '60%',
  },
  categoryName: {
    fontFamily: 'DMSans_400Regular',
    fontSize: ms(14),
    lineHeight: ms(20),
    color: '#000000',
    textAlign: 'center',
    marginTop: vs(4),
  },
  trendingScroll: {
    paddingLeft: s(20),
    paddingRight: s(10),
  },
  cropCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: s(14),
    borderWidth: 1.5,
    borderColor: 'rgba(235, 235, 235, 0.75)',
    paddingTop: vs(20),
    paddingHorizontal: s(14),
    paddingBottom: vs(14),
    marginRight: s(10),
    width: s(150),
    height: vs(191),
    alignItems: 'center',
  },
  cropImage: {
    width: '90%',
    height: vs(85),
    marginBottom: vs(12),
  },
  cropNameRatingRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    width: '100%',
    marginBottom: vs(4),
  },
  cropName: {
    fontFamily: 'DMSans_400Regular',
    fontSize: ms(14),
    lineHeight: ms(18),
    color: '#000000',
  },
  distanceRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  cropDistanceRow: {
    flexDirection: 'row',
    alignItems: 'center',
    width: '100%',
    marginBottom: vs(8),
  },
  distanceText: {
    fontFamily: 'DMSans_400Regular',
    fontSize: ms(12),
    lineHeight: ms(16),
    color: '#898989',
    marginLeft: s(4),
  },
  ratingRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  ratingText: {
    fontFamily: 'DMSans_400Regular',
    fontSize: ms(14),
    lineHeight: ms(18),
    color: '#000000',
    marginLeft: s(4),
  },
  priceRow: {
    flexDirection: 'row',
    alignItems: 'center',
    width: '100%',
  },
  priceSymbol: {
    fontFamily: 'DMSans_700Bold',
    fontSize: ms(15),
    lineHeight: ms(20),
    color: '#4CAF50',
  },
  priceValue: {
    fontFamily: 'DMSans_700Bold',
    fontSize: ms(15),
    lineHeight: ms(20),
    color: '#4CAF50',
  },
  priceUnit: {
    fontFamily: 'DMSans_400Regular',
    fontSize: ms(15),
    lineHeight: ms(20),
    color: '#000000',
  },
  farmersScroll: {
    paddingLeft: s(20),
    paddingRight: s(10),
  },
  farmerCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: s(14),
    marginRight: s(10),
    width: s(187),
    height: vs(200),
  },
  farmerImageContainer: {
    height: vs(102),
    backgroundColor: '#EBEBEB',
    borderTopLeftRadius: s(14),
    borderTopRightRadius: s(14),
    justifyContent: 'flex-start',
    alignItems: 'flex-start',
    paddingLeft: s(149),
    paddingTop: vs(64),
  },
  farmerImage: {
    ...StyleSheet.absoluteFill,
    borderTopLeftRadius: s(14),
    borderTopRightRadius: s(14),
  },
  verifiedBadge: {
    width: s(38),
    height: s(38),
    backgroundColor: '#FFFFFF',
    borderRadius: s(19),
    alignItems: 'center',
    justifyContent: 'center',
  },
  farmerInfo: {
    padding: s(14),
    borderBottomWidth: 1.5,
    borderLeftWidth: 1.5,
    borderRightWidth: 1.5,
    borderColor: '#EBEBEB',
    borderBottomLeftRadius: s(14),
    borderBottomRightRadius: s(14),
    height: vs(98),
  },
  farmerName: {
    fontFamily: 'DMSans_500Medium',
    fontSize: ms(14),
    lineHeight: ms(20),
    color: '#000000',
    marginBottom: vs(4),
  },
  farmerMetaRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: vs(8),
  },
  farmerRatingRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  farmerRatingText: {
    fontFamily: 'DMSans_400Regular',
    fontSize: ms(14),
    lineHeight: ms(18),
    color: '#898989',
    marginLeft: s(4),
  },
  farmerReviewsText: {
    fontFamily: 'DMSans_400Regular',
    fontSize: ms(14),
    lineHeight: ms(18),
    color: '#898989',
    marginLeft: s(2),
  },
  activeListingsText: {
    fontFamily: 'DMSans_400Regular',
    fontSize: ms(14),
    lineHeight: ms(20),
    color: '#4CAF50',
  },
});
