import { Platform, StyleSheet } from 'react-native';
import { s, vs, ms } from '@/utils/scale';

export const styles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: '#FAFAF9',
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: s(20),
    marginTop: vs(30),
    marginBottom: vs(20),
    gap: s(10),
  },
  backButton: {
    width: s(48),
    height: s(48),
    borderRadius: s(15),
    backgroundColor: '#4CAF50',
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerTitle: {
    fontFamily: 'DMSans_500Medium',
    fontSize: ms(18),
    lineHeight: ms(23),
    color: '#000000',
  },
  tabsContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: s(8),
    marginHorizontal: s(20),
    backgroundColor: '#FFFFFF',
    borderWidth: 1.5,
    borderColor: '#EBEBEB',
    borderRadius: s(14),
    marginBottom: vs(20),
  },
  tab: {
    flex: 1,
    height: vs(38),
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: s(12),
  },
  tabActive: {
    backgroundColor: '#4CAF50',
  },
  tabText: {
    fontFamily: 'DMSans_500Medium',
    fontSize: ms(16),
    color: '#000000',
  },
  tabTextActive: {
    color: '#FFFFFF',
  },
  listContainer: {
    paddingHorizontal: s(20),
    paddingBottom: vs(100),
    gap: vs(10),
  },
  orderCard: {
    backgroundColor: '#FFFFFF',
    borderWidth: 1.5,
    borderColor: '#EBEBEB',
    borderRadius: s(14),
    padding: s(16),
    marginBottom: vs(18),
  },
  cardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: vs(12),
  },
  orderedByCol: {
    flexDirection: 'column',
    gap: vs(4),
  },
  orderedByLabel: {
    fontFamily: 'DMSans_400Regular',
    fontSize: ms(14),
    color: '#898989',
    lineHeight: ms(18),
  },
  listCustomerName: {
    fontFamily: 'DMSans_500Medium',
    fontSize: ms(16),
    color: '#000000',
    lineHeight: ms(21),
  },
  statusText: {
    fontFamily: 'DMSans_400Regular',
    fontSize: ms(14),
    lineHeight: ms(18),
  },
  cardBody: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: s(15),
  },
  avatar: {
    width: s(100),
    height: s(100),
    borderRadius: s(20),
  },
  productDetails: {
    flex: 1,
    flexDirection: 'column',
    gap: vs(8),
  },
  productNameWeight: {
    flexDirection: 'column',
    gap: vs(1),
  },
  productName: {
    fontFamily: 'DMSans_500Medium',
    fontSize: ms(14),
    color: '#000000',
    lineHeight: ms(20),
  },
  productWeight: {
    fontFamily: 'DMSans_500Medium',
    fontSize: ms(14),
    color: '#000000',
    lineHeight: ms(20),
  },
  locationRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: s(10),
  },
  locationText: {
    fontFamily: 'DMSans_400Regular',
    fontSize: ms(14),
    color: '#898989',
    lineHeight: ms(20),
  },
  locationIconBox: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: s(2),
  },
  distanceText: {
    fontFamily: 'DMSans_400Regular',
    fontSize: ms(14),
    color: '#898989',
    lineHeight: ms(18),
  },
  priceRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: s(4),
    marginTop: vs(4),
  },
  priceText: {
    fontFamily: 'DMSans_700Bold',
    fontSize: ms(18),
    color: '#4CAF50',
    lineHeight: ms(23),
  },
  orderIdRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: s(4),
    marginTop: vs(18),
  },
  orderIdLabel: {
    fontFamily: 'DMSans_400Regular',
    fontSize: ms(14),
    color: '#898989',
    lineHeight: ms(18),
  },
  orderIdValue: {
    fontFamily: 'DMSans_400Regular',
    fontSize: ms(14),
    color: '#000000',
    lineHeight: ms(18),
  },
  bottomBar: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    height: vs(84),
    backgroundColor: '#FFFFFF',
    flexDirection: 'row',
    justifyContent: 'space-around',
    alignItems: 'center',
    paddingHorizontal: s(10),
    paddingBottom: vs(20),
    ...Platform.select({
      ios: {
        shadowColor: 'rgba(76, 175, 80, 0.15)',
        shadowOffset: { width: 0, height: 0 },
        shadowOpacity: 1,
        shadowRadius: 4,
      },
      android: {
        elevation: 8,
      },
      web: {
        boxShadow: '0px 0px 4px rgba(76, 175, 80, 0.15)',
      },
    }),
  },
  tabItem: {
    alignItems: 'center',
    justifyContent: 'center',
    width: s(60),
    gap: vs(3),
  },
  tabIconBox: {
    width: s(32),
    height: s(32),
    alignItems: 'center',
    justifyContent: 'center',
  },
  tabIcon: {
    width: '100%',
    height: '100%',
  },
  tabLabel: {
    fontFamily: 'DMSans_400Regular',
    fontSize: ms(14),
    lineHeight: ms(18),
    color: '#737373',
  },
  tabLabelActive: {
    color: '#4CAF50',
  },
  detailsContainer: {
    padding: s(20),
    gap: vs(20),
    paddingBottom: vs(40),
  },
  bannerCompleted: {
    backgroundColor: '#4CAF50',
    borderRadius: s(14),
    paddingVertical: vs(14),
    alignItems: 'center',
    justifyContent: 'center',
  },
  bannerCancelled: {
    backgroundColor: '#E62326',
    borderRadius: s(14),
    paddingVertical: vs(14),
    alignItems: 'center',
    justifyContent: 'center',
  },
  bannerText: {
    fontFamily: 'DMSans_400Regular',
    fontSize: ms(16),
    color: '#FFFFFF',
  },
  customerCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: s(14),
    padding: s(10),
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: vs(20),
    borderWidth: 1.5,
    borderColor: '#EBEBEB',
    gap: s(15),
  },
  customerInfo: {
    flex: 1,
    gap: vs(4),
  },
  customerName: {
    fontFamily: 'DMSans_500Medium',
    fontSize: ms(18),
    color: '#000000',
  },
  customerLocation: {
    fontFamily: 'DMSans_400Regular',
    fontSize: ms(14),
    color: '#8C8C8C',
  },
  actionButtons: {
    flexDirection: 'row',
    gap: s(10),
  },
  btnReject: {
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'center',
    gap: s(6),
    backgroundColor: '#FFFFFF',
    borderWidth: 1.5,
    borderColor: '#4CAF50',
    borderRadius: s(14),
    paddingVertical: vs(14),
    alignItems: 'center',
  },
  btnRejectText: {
    color: '#000000',
    fontFamily: 'DMSans_500Medium',
    fontSize: ms(16),
  },
  btnAccept: {
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'center',
    gap: s(6),
    backgroundColor: '#4CAF50',
    borderRadius: s(14),
    paddingVertical: vs(14),
    alignItems: 'center',
  },
  btnAcceptText: {
    color: '#FFFFFF',
    fontFamily: 'DMSans_500Medium',
    fontSize: ms(16),
  },
  summaryContainer: {
    backgroundColor: '#FFFFFF',
    borderRadius: s(14),
    padding: s(14),
    borderWidth: 1.5,
    borderColor: '#EBEBEB',
    gap: vs(10),
  },
  summaryBox: {
    backgroundColor: '#FFFFFF',
    borderRadius: s(14),
    paddingHorizontal: s(18),
    paddingVertical: vs(15),
    borderWidth: 1.5,
    borderColor: '#EBEBEB',
  },
  summaryTitle: {
    fontFamily: 'DMSans_500Medium',
    fontSize: ms(16),
    marginBottom: vs(12),
    color: '#000000',
  },
  summaryRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: vs(12),
  },
  summaryLabel: {
    fontFamily: 'DMSans_400Regular',
    fontSize: ms(14),
    color: '#6D6D6D',
  },
  summaryValue: {
    fontFamily: 'DMSans_500Medium',
    fontSize: ms(14),
    color: '#000000',
  },
  totalBox: {
    backgroundColor: '#FFFFFF',
    borderRadius: s(14),
    paddingHorizontal: s(18),
    paddingVertical: vs(15),
    borderWidth: 1.5,
    borderColor: '#EBEBEB',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  totalLabel: {
    fontFamily: 'DMSans_500Medium',
    fontSize: ms(16),
    color: '#000000',
  },
  totalValue: {
    fontFamily: 'DMSans_700Bold',
    fontSize: ms(20),
    color: '#000000',
  },
  totalBoxCompleted: {
    backgroundColor: '#4CAF50',
    borderRadius: s(14),
    paddingVertical: vs(16),
    paddingHorizontal: s(20),
    marginTop: vs(10),
    gap: vs(8),
  },
  totalRowCompleted: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: s(10),
  },
  totalLabelCompleted: {
    fontFamily: 'DMSans_400Regular',
    fontSize: ms(16),
    color: '#FFFFFF',
  },
  totalValueCompleted: {
    fontFamily: 'DMSans_400Regular',
    fontSize: ms(16),
    color: '#FFFFFF',
  },
  completedOnText: {
    fontFamily: 'DMSans_400Regular',
    fontSize: ms(16),
    color: '#FFFFFF',
  },
  trackBtn: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    gap: s(10),
    backgroundColor: '#4CAF50',
    borderRadius: s(14),
    paddingVertical: vs(16),
    marginTop: vs(20),
  },
  trackBtnText: {
    color: '#FFFFFF',
    fontFamily: 'DMSans_500Medium',
    fontSize: ms(16),
  },
  fixedBottomBar: {
    padding: s(20),
    backgroundColor: '#FAFAF9',
    paddingBottom: vs(40),
  },
  orderMeta: {
    alignItems: 'flex-end',
    justifyContent: 'center',
    minWidth: s(80),
  },
  orderTime: {
    fontFamily: 'DMSans_400Regular',
    fontSize: ms(12),
    lineHeight: ms(16),
    color: '#8C8C8C',
  },
});
