import { StyleSheet } from 'react-native';

export const onboardingStyles = StyleSheet.create({
  root: {
    flex: 1,
    backgroundColor: '#ffffff',
  },
  keyboardView: {
    flex: 1,
  },
  scrollContent: {
    flexGrow: 1,
    alignItems: 'center',
    backgroundColor: '#ffffff',
  },
  phoneCanvas: {
    width: '100%',
    minHeight: '100%',
    backgroundColor: '#ffffff',
  },
  screen: {
    flex: 1,
    backgroundColor: '#FAFAF9',
    paddingHorizontal: 20,
    position: 'relative',
  },
  gradientTop: {
    position: 'absolute',
    left: 0,
    right: 0,
    top: 0,
    height: 200,
  },
  welcomeScreen: {
    justifyContent: 'space-between',
    paddingTop: 60,
    paddingBottom: 26,
  },
  header: {
    height: 44,
    justifyContent: 'center',
    paddingHorizontal: 20,
    paddingTop: 6,
  },
  backButton: {
    width: 34,
    height: 34,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 17,
    backgroundColor: '#f1f5ef',
  },
  backText: {
    color: '#1b1b1b',
    fontSize: 22,
    lineHeight: 24,
    fontWeight: '600',
  },
  invisible: {
    opacity: 0,
  },
  tintHeader: {
    position: 'absolute',
    left: 0,
    right: 0,
    top: 0,
    height: 136,
    backgroundColor: '#dff4e0',
  },
  headerIcon: {
    width: 65,
    height: 65,
    marginTop: 35,
    marginBottom: 15, // 115 - 35 - 65 = 15
  },
  heroCluster: {
    height: 160,
    alignItems: 'center',
    justifyContent: 'center',
    position: 'relative',
    display: 'none',
  },
  tomatoBubble: {
    position: 'absolute',
    left: '5%',
    top: '3%',
    width: 120,
    height: 120,
    borderRadius: 60,
    overflow: 'hidden',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.12,
    shadowRadius: 12,
    elevation: 6,
  },
  ricePill: {
    position: 'absolute',
    right: '5%',
    top: '9%',
    width: 100,
    height: 200,
    borderRadius: 80,
    overflow: 'hidden',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.08,
    shadowRadius: 12,
    elevation: 4,
  },
  greenBubble: {
    position: 'absolute',
    right: '5%',
    bottom: '22%',
    width: 120,
    height: 120,
    borderRadius: 60,
    overflow: 'hidden',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.08,
    shadowRadius: 10,
    elevation: 4,
  },
  fieldPill: {
    position: 'absolute',
    left: '14%',
    bottom: '6%',
    width: '73%',
    height: 100,
    borderRadius: 80,
    overflow: 'hidden',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.12,
    shadowRadius: 18,
    elevation: 6,
  },
  frame: {
    flex: 1,
    borderWidth: 4,
    borderColor: '#0b72a6',
    borderRadius: 8,
    padding: 6,
    backgroundColor: '#ffffff',
  },
  brandBlock: {
    position: 'absolute',
    top: '40%',
    left: 0,
    right: 0,
    alignItems: 'center',
    paddingHorizontal: 20,
    zIndex: 10,
  },
  brandTitle: {
    color: '#307032',
    fontSize: 35,
    lineHeight: 42,
    fontWeight: '600', // Approximation of 510 SF Pro
    marginBottom: 12,
  },
  brandCopy: {
    color: '#3F9542',
    fontFamily: 'DMSans_400Regular',
    fontSize: 25,
    lineHeight: 33,
    textAlign: 'center',
  },
  copyBlock: {
    gap: 4,
    marginBottom: 20,
  },
  title: {
    color: '#000000',
    fontFamily: 'Poppins_600SemiBold',
    fontSize: 27,
    lineHeight: 40,
  },
  subcopy: {
    color: '#525252',
    fontFamily: 'DMSans_400Regular',
    fontSize: 20,
    lineHeight: 26,
  },
  roleGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 16,
    justifyContent: 'center',
  },
  roleCard: {
    width: '46%',
    minHeight: 160,
    borderRadius: 10,
    backgroundColor: '#ffffff',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 14,
    shadowColor: '#173719',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.08,
    shadowRadius: 16,
    elevation: 4,
  },
  roleImageWrap: {
    width: 74,
    height: 74,
    borderRadius: 12,
    overflow: 'hidden',
    marginBottom: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  roleImage: {
    width: '100%',
    height: '100%',
  },
  roleLabel: {
    color: '#1a1a1a',
    fontSize: 13,
    fontWeight: '800',
  },
  roleCaption: {
    color: '#777777',
    fontSize: 10,
    marginTop: 2,
  },
  formStack: {
    gap: 12,
  },
  formGroup: {
    borderWidth: 1.5,
    borderColor: '#EBEBEB',
    borderRadius: 14,
    paddingTop: 15,
    paddingHorizontal: 20,
    paddingBottom: 18,
    backgroundColor: '#FFFFFF',
    gap: 4,
    marginBottom: 12,
  },
  inputLabel: {
    color: '#6D6D6D',
    fontFamily: 'DMSans_400Regular',
    fontSize: 14,
    lineHeight: 18,
  },
  input: {
    color: '#000000',
    fontFamily: 'DMSans_500Medium',
    fontSize: 16,
    lineHeight: 21,
    padding: 0,
    margin: 0,
    outlineWidth: 0,
  },
  formGroupError: {
    borderColor: '#E62326',
  },
  errorBlock: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    paddingVertical: 10,
    paddingHorizontal: 12,
    gap: 10,
    backgroundColor: 'rgba(230, 35, 38, 0.15)',
    borderRadius: 12,
    marginTop: 4,
  },
  errorText: {
    color: '#E62326',
    fontFamily: 'Outfit_400Regular',
    fontSize: 14,
    lineHeight: 18,
  },
  otpRow: {
    flexDirection: 'row',
    gap: 13,
    marginTop: 8,
  },
  otpInput: {
    width: 40,
    height: 40,
    borderRadius: 12,
    backgroundColor: '#def1df',
    color: '#1e652c',
    textAlign: 'center',
    fontSize: 18,
    fontWeight: '800',
    outlineWidth: 0,
  },
  footer: {
    position: 'absolute',
    bottom: 50,
    left: 20,
    right: 20,
  },
  primaryButton: {
    height: 50,
    borderRadius: 14,
    backgroundColor: '#4CAF50',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 14,
    paddingHorizontal: 16,
  },
  primaryButtonText: {
    color: '#FFFFFF',
    fontFamily: 'DMSans_500Medium',
    fontSize: 15,
    lineHeight: 20,
  },
  resendText: {
    color: '#93a092',
    textAlign: 'center',
    fontSize: 11,
    marginTop: 14,
  },
  pressed: {
    opacity: 0.75,
  },
  actionContainer: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    opacity: 0,
    zIndex: 10,
    justifyContent: 'center',
  },
});
