import { StyleSheet, Dimensions } from 'react-native';
import { s, vs, ms } from '@/utils/scale';

const SCREEN_HEIGHT = Dimensions.get('window').height;
const fh = (h: number) => (h / 917) * SCREEN_HEIGHT;

export const onboardingStyles = StyleSheet.create({
  root: {
    flex: 1,
    backgroundColor: '#ffffff',
  },
  keyboardView: {
    flex: 1,
  },
  scrollContent: {
    flexGrow: 1,
    alignItems: 'center',
    backgroundColor: '#ffffff',
  },
  phoneCanvas: {
    width: '100%',
    minHeight: '100%',
    backgroundColor: '#ffffff',
  },
  screen: {
    flex: 1,
    backgroundColor: '#FAFAF9',
    paddingHorizontal: s(20),
    position: 'relative',
  },
  gradientTop: {
    position: 'absolute',
    left: 0,
    right: 0,
    top: 0,
    height: vs(200),
  },
  welcomeScreen: {
    justifyContent: 'space-between',
    paddingTop: vs(60),
    paddingBottom: vs(26),
  },
  header: {
    height: vs(44),
    justifyContent: 'center',
    paddingHorizontal: s(20),
    paddingTop: vs(6),
  },
  backButton: {
    width: s(34),
    height: s(34),
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: s(17),
    backgroundColor: '#f1f5ef',
  },
  backText: {
    color: '#1b1b1b',
    fontSize: ms(22),
    lineHeight: ms(24),
    fontWeight: '600',
  },
  invisible: {
    opacity: 0,
  },
  tintHeader: {
    position: 'absolute',
    left: 0,
    right: 0,
    top: 0,
    height: vs(136),
    backgroundColor: '#dff4e0',
  },
  headerIcon: {
    width: s(65),
    height: s(65),
    marginTop: vs(35),
    marginBottom: vs(15),
  },
  heroCluster: {
    height: vs(160),
    alignItems: 'center',
    justifyContent: 'center',
    position: 'relative',
    display: 'none',
  },
  tomatoBubble: {
    position: 'absolute',
    left: '5%',
    top: '3%',
    width: s(120),
    height: s(120),
    borderRadius: s(60),
    overflow: 'hidden',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.12,
    shadowRadius: 12,
    elevation: 6,
  },
  ricePill: {
    position: 'absolute',
    right: '5%',
    top: '9%',
    width: s(100),
    height: vs(200),
    borderRadius: s(80),
    overflow: 'hidden',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.08,
    shadowRadius: 12,
    elevation: 4,
  },
  greenBubble: {
    position: 'absolute',
    right: '5%',
    bottom: '22%',
    width: s(120),
    height: s(120),
    borderRadius: s(60),
    overflow: 'hidden',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.08,
    shadowRadius: 10,
    elevation: 4,
  },
  fieldPill: {
    position: 'absolute',
    left: '14%',
    bottom: '6%',
    width: '73%',
    height: vs(100),
    borderRadius: s(80),
    overflow: 'hidden',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.12,
    shadowRadius: 18,
    elevation: 6,
  },
  frame: {
    flex: 1,
    borderWidth: 4,
    borderColor: '#0b72a6',
    borderRadius: s(8),
    padding: s(6),
    backgroundColor: '#ffffff',
  },
  brandBlock: {
    position: 'absolute',
    top: '40%',
    left: 0,
    right: 0,
    alignItems: 'center',
    paddingHorizontal: s(20),
    zIndex: 10,
  },
  brandTitle: {
    color: '#307032',
    fontSize: ms(35),
    lineHeight: ms(42),
    fontWeight: '600',
    marginBottom: vs(12),
  },
  brandCopy: {
    color: '#3F9542',
    fontFamily: 'DMSans_400Regular',
    fontSize: ms(25),
    lineHeight: ms(33),
    textAlign: 'center',
  },
  copyBlock: {
    gap: vs(4),
    marginBottom: vs(20),
  },
  title: {
    color: '#000000',
    fontFamily: 'Poppins_600SemiBold',
    fontSize: ms(27),
    lineHeight: ms(40),
  },
  subcopy: {
    color: '#525252',
    fontFamily: 'DMSans_400Regular',
    fontSize: ms(20),
    lineHeight: ms(26),
  },
  roleGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: s(16),
    justifyContent: 'center',
  },
  roleCard: {
    width: '46%',
    minHeight: vs(160),
    borderRadius: s(10),
    backgroundColor: '#ffffff',
    alignItems: 'center',
    justifyContent: 'center',
    padding: s(14),
    shadowColor: '#173719',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.08,
    shadowRadius: 16,
    elevation: 4,
  },
  roleImageWrap: {
    width: s(74),
    height: s(74),
    borderRadius: s(12),
    overflow: 'hidden',
    marginBottom: vs(12),
    alignItems: 'center',
    justifyContent: 'center',
  },
  roleImage: {
    width: '100%',
    height: '100%',
  },
  roleLabel: {
    color: '#1a1a1a',
    fontSize: ms(13),
    fontWeight: '800',
  },
  roleCaption: {
    color: '#777777',
    fontSize: ms(10),
    marginTop: vs(2),
  },
  formStack: {
    gap: vs(12),
  },
  formGroup: {
    borderWidth: 1.5,
    borderColor: '#EBEBEB',
    borderRadius: s(14),
    paddingTop: vs(15),
    paddingHorizontal: s(20),
    paddingBottom: vs(18),
    backgroundColor: '#FFFFFF',
    gap: vs(4),
    marginBottom: vs(12),
  },
  inputLabel: {
    color: '#6D6D6D',
    fontFamily: 'DMSans_400Regular',
    fontSize: ms(14),
    lineHeight: ms(18),
  },
  input: {
    color: '#000000',
    fontFamily: 'DMSans_500Medium',
    fontSize: ms(16),
    lineHeight: ms(21),
    padding: 0,
    margin: 0,
    outlineWidth: 0,
  },
  formGroupError: {
    borderColor: '#E62326',
  },
  errorBlock: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    paddingVertical: vs(10),
    paddingHorizontal: s(12),
    gap: s(10),
    backgroundColor: 'rgba(230, 35, 38, 0.15)',
    borderRadius: s(12),
    marginTop: vs(4),
  },
  errorText: {
    color: '#E62326',
    fontFamily: 'Outfit_400Regular',
    fontSize: ms(14),
    lineHeight: ms(18),
  },
  otpRow: {
    flexDirection: 'row',
    gap: s(13),
    marginTop: vs(8),
  },
  otpInput: {
    width: s(40),
    height: s(40),
    borderRadius: s(12),
    backgroundColor: '#def1df',
    color: '#1e652c',
    textAlign: 'center',
    fontSize: ms(18),
    fontWeight: '800',
    outlineWidth: 0,
  },
  footer: {
    position: 'absolute',
    bottom: vs(50),
    left: s(20),
    right: s(20),
  },
  primaryButton: {
    height: vs(50),
    borderRadius: s(14),
    backgroundColor: '#4CAF50',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: vs(14),
    paddingHorizontal: s(16),
  },
  primaryButtonText: {
    color: '#FFFFFF',
    fontFamily: 'DMSans_500Medium',
    fontSize: ms(15),
    lineHeight: ms(20),
  },
  resendText: {
    color: '#93a092',
    textAlign: 'center',
    fontSize: ms(11),
    marginTop: vs(14),
  },
  pressed: {
    opacity: 0.75,
  },
  // --- Role Screen ---
  roleBgContainer: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    height: '100%',
    zIndex: -1,
  },
  roleBgImage: {
    position: 'absolute',
    top: 0,
    left: 0,
    width: '100%',
    height: vs(414),
  },
  roleBgGradient: {
    position: 'absolute',
    left: 0,
    right: 0,
    top: vs(150),
    bottom: 0,
  },
  roleScrollContent: {
    flex: 1,
  },
  roleScrollContainer: {
    flexGrow: 1,
    paddingBottom: vs(20),
  },
  roleTopSection: {
    alignItems: 'center',
    marginTop: vs(78),
    marginBottom: vs(119),
  },
  roleHeaderContainer: {
    alignItems: 'center',
    marginBottom: vs(43),
  },
  roleWelcomeText: {
    fontFamily: 'Poppins_400Regular',
    fontSize: ms(16),
    color: '#000000',
    lineHeight: ms(24),
    textAlign: 'center',
  },
  roleBrandText: {
    fontFamily: 'Poppins_500Medium',
    fontSize: ms(22),
    color: '#4CAF50',
    lineHeight: ms(33),
    textAlign: 'center',
  },
  roleTitleContainer: {
    alignItems: 'center',
    gap: vs(2),
  },
  roleTitle: {
    fontFamily: 'Poppins_500Medium',
    fontSize: ms(20),
    color: '#000000',
    lineHeight: ms(30),
    textAlign: 'center',
  },
  roleSubtitle: {
    fontFamily: 'DMSans_400Regular',
    fontSize: ms(15),
    color: '#000000',
    lineHeight: ms(20),
    textAlign: 'center',
  },
  roleList: {
    gap: vs(12),
  },
  roleListCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderWidth: 1.5,
    borderColor: '#EBEBEB',
    borderRadius: s(14),
    paddingVertical: vs(14),
    paddingHorizontal: s(16),
    gap: s(15),
  },
  roleListCardSelected: {
    backgroundColor: '#FAFAF9',
  },
  roleListImage: {
    width: s(159),
    aspectRatio: 159 / 106,
    borderRadius: s(15),
  },
  roleListTextContent: {
    flex: 1,
    gap: vs(2),
  },
  roleListLabel: {
    fontFamily: 'DMSans_500Medium',
    fontSize: ms(16),
    color: '#000000',
    lineHeight: ms(21),
  },
  roleListCaption: {
    fontFamily: 'DMSans_400Regular',
    fontSize: ms(12),
    lineHeight: ms(19),
    color: '#000000',
  },
  roleActionContainer: {
    paddingHorizontal: s(20),
    marginTop: 'auto',
    marginBottom: vs(20),
  },

  // ─── Authentication Method Screen ───
  actionContainer: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    opacity: 0,
    zIndex: 10,
    justifyContent: 'center',
  },

  // --- Auth Method Screen ---
  authBgContainer: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    height: '100%',
    zIndex: -1,
    backgroundColor: '#FAFAF9',
  },
  authBgImage: {
    position: 'absolute',
    top: 0,
    left: 0,
    width: '100%',
    height: vs(548),
  },
  authTopSection: {
    alignItems: 'center',
    paddingTop: vs(103),
  },
  authBrandTitle: {
    fontFamily: 'Poppins_500Medium',
    fontSize: ms(20),
    color: '#4CAF50',
    lineHeight: ms(30),
    textAlign: 'center',
  },
  authBrandSubtitle: {
    fontFamily: 'DMSans_400Regular',
    fontSize: ms(14),
    color: '#000000',
    lineHeight: ms(19),
    textAlign: 'center',
  },
  authBottomSheet: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    height: vs(473),
    backgroundColor: '#FFFFFF',
    borderTopLeftRadius: s(24),
    borderTopRightRadius: s(24),
    alignItems: 'center',
    paddingTop: vs(30),
  },
  authWelcomeTitle: {
    fontFamily: 'DMSans_500Medium',
    fontSize: ms(18),
    color: '#000000',
    lineHeight: ms(23),
    textAlign: 'center',
    marginBottom: vs(4),
  },
  authWelcomeSubtitle: {
    fontFamily: 'DMSans_400Regular',
    fontSize: ms(14),
    color: '#898989',
    lineHeight: ms(18),
    textAlign: 'center',
    marginBottom: vs(20),
  },
  authCard: {
    width: s(372),
    height: vs(73),
    backgroundColor: '#FFFFFF',
    borderWidth: 1.5,
    borderColor: '#4CAF50',
    borderRadius: s(14),
    paddingHorizontal: s(16),
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: vs(25),
  },
  authCardIconBox: {
    width: s(40),
    height: s(40),
    backgroundColor: 'rgba(76, 175, 80, 0.1)',
    borderRadius: s(8),
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: s(14),
  },
  authCardTextContent: {
    flex: 1,
    justifyContent: 'center',
  },
  authCardTitle: {
    fontFamily: 'DMSans_400Regular',
    fontSize: ms(16),
    color: '#000000',
    lineHeight: ms(21),
    marginBottom: vs(4),
  },
  authCardSubtitle: {
    fontFamily: 'DMSans_400Regular',
    fontSize: ms(14),
    color: '#898989',
    lineHeight: ms(18),
  },
  authSecurityBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    width: s(372),
    height: vs(48),
    backgroundColor: 'rgba(76, 175, 80, 0.1)',
    borderRadius: s(14),
    position: 'absolute',
    bottom: vs(80),
  },
  authSecurityText: {
    fontFamily: 'DMSans_400Regular',
    fontSize: ms(14),
    color: '#4CAF50',
    marginLeft: s(10),
  },
  authHelpTextContainer: {
    position: 'absolute',
    bottom: vs(34),
    flexDirection: 'row',
  },
  authHelpText: {
    fontFamily: 'DMSans_400Regular',
    fontSize: ms(14),
    color: '#898989',
  },
  authHelpTextLink: {
    fontFamily: 'DMSans_400Regular',
    fontSize: ms(14),
    color: '#4CAF50',
  },
// ─── Pan Card Screen ───
panScreen: {
  flex: 1,
    backgroundColor: '#FAFAF9',
      paddingHorizontal: s(20),
  },
panProgressContainer: {
  flexDirection: 'row',
    gap: s(7),
      marginTop: vs(40),
        marginBottom: vs(25),
  },
panProgressBarActive: {
  flex: 1,
    height: vs(5),
      backgroundColor: '#4CAF50',
        borderRadius: s(15),
  },
panProgressBarInactive: {
  flex: 1,
    height: vs(5),
      backgroundColor: '#EBEBEB',
        borderRadius: s(15),
  },
panHeaderSection: {
  marginBottom: vs(15),
  },
panTitle: {
  fontFamily: 'Poppins_600SemiBold',
    fontSize: ms(27),
      color: '#000000',
        lineHeight: ms(40),
          marginBottom: vs(4),
  },
panSubtitle: {
  fontFamily: 'DMSans_400Regular',
    fontSize: ms(20),
      color: '#525252',
        lineHeight: ms(26),
  },
panInputContainer: {
  backgroundColor: '#FFFFFF',
    borderWidth: 1.5,
      borderColor: '#EBEBEB',
        borderRadius: s(14),
          paddingVertical: vs(15),
            paddingHorizontal: s(20),
              marginBottom: vs(25),
  },
panInputLabel: {
  fontFamily: 'DMSans_400Regular',
    fontSize: ms(14),
      color: '#6D6D6D',
        lineHeight: ms(18),
          marginBottom: vs(4),
  },
panInput: {
  fontFamily: 'DMSans_500Medium',
    fontSize: ms(16),
      color: '#000000',
        padding: 0,
          margin: 0,
  },
panUploadSection: {
  marginBottom: vs(20),
  },
panUploadTitle: {
  fontFamily: 'DMSans_500Medium',
    fontSize: ms(16),
      color: '#000000',
        lineHeight: ms(21),
          marginBottom: vs(10),
  },
panUploadBox: {
  backgroundColor: '#FFFFFF',
    borderWidth: 1.5,
      borderColor: '#EBEBEB',
        borderStyle: 'dashed',
          borderRadius: s(14),
            height: vs(150),
              justifyContent: 'center',
                alignItems: 'center',
                  gap: vs(10),
                    overflow: 'hidden',
  },
panUploadBoxRow: {
  flexDirection: 'row',
    justifyContent: 'space-between',
      paddingHorizontal: s(20),
  },
panPreviewImage: {
  width: s(120),
    height: vs(80),
      borderRadius: s(8),
        borderWidth: 1,
          borderColor: '#EBEBEB',
  },
panUploadTextContainer: {
  alignItems: 'center',
    gap: vs(4),
  },
panUploadIconBox: {
  width: s(32),
    height: s(32),
      backgroundColor: '#D9D9D9',
        borderRadius: s(16),
          justifyContent: 'center',
            alignItems: 'center',
              marginBottom: vs(4),
  },
panUploadLabel: {
  fontFamily: 'DMSans_400Regular',
    fontSize: ms(14),
      color: '#000000',
        lineHeight: ms(18),
  },
panUploadHint: {
  fontFamily: 'DMSans_400Regular',
    fontSize: ms(12),
      color: '#898989',
        lineHeight: ms(16),
  },
panFooter: {
  marginTop: 'auto',
    marginBottom: vs(30),
      alignItems: 'center',
  },
panContinueButton: {
  width: '100%',
    height: vs(50),
      backgroundColor: 'rgba(76, 175, 80, 0.5)',
        borderRadius: s(14),
          justifyContent: 'center',
            alignItems: 'center',
              marginBottom: vs(15),
  },
panContinueButtonText: {
  fontFamily: 'DMSans_500Medium',
    fontSize: ms(15),
      color: '#FFFFFF',
  },
panFooterHint: {
  fontFamily: 'Outfit_400Regular',
    fontSize: ms(14),
      color: '#686868',
        lineHeight: ms(18),
  },
});
