import { StyleSheet, Platform } from 'react-native';

export const styles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: '#FAFAF9',
  },
  scrollContent: {
    paddingBottom: 120, // space for bottom download button + navbar
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    marginTop: Platform.OS === 'ios' ? 50 : 30,
    marginBottom: 20,
  },
  headerLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  backButton: {
    width: 48,
    height: 48,
    borderRadius: 15,
    backgroundColor: '#4CAF50',
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerTitle: {
    fontFamily: 'Poppins_500Medium',
    fontSize: 18,
    lineHeight: 27,
    color: '#000000',
  },
  filterButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 10,
    paddingHorizontal: 14,
    gap: 6,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#4CAF50',
    borderRadius: 10,
  },
  filterText: {
    fontFamily: 'DMSans_400Regular',
    fontSize: 12,
    lineHeight: 16,
    color: '#000000',
  },
  gridContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    paddingHorizontal: 20,
    gap: 12,
    marginBottom: 20,
  },
  card: {
    width: '48%', // dynamic width for 2-column grid
    flexGrow: 1,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#4CAF50',
    borderRadius: 10,
    padding: 12,
    gap: 10,
  },
  cardIconBox: {
    width: 36,
    height: 36,
    borderRadius: 8,
    backgroundColor: 'rgba(76, 175, 80, 0.2)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  cardIcon: {
    width: 20,
    height: 20,
  },
  cardLabel: {
    fontFamily: 'DMSans_400Regular',
    fontSize: 14,
    lineHeight: 20,
    color: '#898989',
  },
  cardValueContainer: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  cardValue: {
    fontFamily: 'DMSans_500Medium',
    fontSize: 16,
    lineHeight: 22,
    color: '#000000',
    marginLeft: 2,
  },
  cardTrendRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  cardTrendText: {
    fontFamily: 'DMSans_400Regular',
    fontSize: 12,
    lineHeight: 16,
    color: '#4CAF50',
  },
  cardSubtext: {
    fontFamily: 'DMSans_400Regular',
    fontSize: 12,
    lineHeight: 16,
    color: '#898989',
  },
  chartCard: {
    marginHorizontal: 20,
    backgroundColor: '#FFFFFF',
    borderWidth: 1.5,
    borderColor: '#EBEBEB',
    borderRadius: 14,
    padding: 16,
    gap: 12,
    marginBottom: 20,
  },
  chartTitle: {
    fontFamily: 'DMSans_500Medium',
    fontSize: 16,
    lineHeight: 21,
    color: '#000000',
  },
  chartWrapper: {
    height: 210,
    flexDirection: 'row',
  },
  yAxis: {
    width: 40,
    height: 160,
    justifyContent: 'space-between',
    alignItems: 'flex-start',
  },
  yAxisLabelContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    height: 16,
  },
  yAxisText: {
    fontFamily: 'DMSans_400Regular',
    fontSize: 12,
    lineHeight: 16,
    color: '#898989',
    marginLeft: 2,
  },
  chartPlotArea: {
    flex: 1,
    position: 'relative',
    height: 160,
  },
  gridLinesContainer: {
    position: 'absolute',
    left: 0,
    right: 0,
    top: 0,
    bottom: 0,
    justifyContent: 'space-between',
  },
  gridLine: {
    height: 1,
    backgroundColor: '#EBEBEB',
    width: '100%',
  },
  barsContainer: {
    position: 'absolute',
    left: 0,
    right: 0,
    top: 0,
    bottom: 0,
    flexDirection: 'row',
    justifyContent: 'space-around',
    alignItems: 'flex-end',
    paddingHorizontal: 10,
  },
  barCol: {
    alignItems: 'center',
    justifyContent: 'flex-end',
    height: '100%',
  },
  barVal: {
    fontFamily: 'DMSans_400Regular',
    fontSize: 12,
    lineHeight: 16,
    color: '#000000',
    marginBottom: 4,
  },
  bar: {
    width: 25,
    backgroundColor: 'rgba(76, 175, 80, 0.8)',
    borderTopLeftRadius: 5,
    borderTopRightRadius: 5,
  },
  xAxis: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    paddingLeft: 40, // align with bars container
    marginTop: 10,
  },
  xAxisText: {
    fontFamily: 'DMSans_400Regular',
    fontSize: 12,
    lineHeight: 16,
    color: '#898989',
    width: 60,
    textAlign: 'center',
  },
  sectionTitle: {
    fontFamily: 'DMSans_500Medium',
    fontSize: 16,
    lineHeight: 21,
    color: '#000000',
    marginHorizontal: 20,
    marginBottom: 12,
  },
  topCropCard: {
    marginHorizontal: 20,
    flexDirection: 'row',
    alignItems: 'center',
    padding: 14,
    backgroundColor: '#FFFFFF',
    borderWidth: 1.5,
    borderColor: '#EBEBEB',
    borderRadius: 14,
    gap: 12,
    marginBottom: 20,
  },
  topCropImage: {
    width: 120,
    height: 120,
    borderRadius: 20,
  },
  topCropDetails: {
    flex: 1,
    gap: 6,
  },
  topCropTitle: {
    fontFamily: 'DMSans_400Regular',
    fontSize: 14,
    lineHeight: 18,
    color: '#000000',
  },
  topCropRow: {
    flexDirection: 'column',
    gap: 2,
  },
  topCropLabel: {
    fontFamily: 'DMSans_400Regular',
    fontSize: 14,
    lineHeight: 18,
    color: '#898989',
  },
  topCropValue: {
    fontFamily: 'DMSans_400Regular',
    fontSize: 14,
    lineHeight: 18,
    color: '#000000',
  },
  topCropRevenueContainer: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  topCropRevenueValue: {
    fontFamily: 'DMSans_500Medium',
    fontSize: 14,
    lineHeight: 18,
    color: '#4CAF50',
    marginLeft: 2,
  },
  recentHeaderRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginHorizontal: 20,
    marginBottom: 12,
  },
  recentTitle: {
    fontFamily: 'DMSans_500Medium',
    fontSize: 16,
    lineHeight: 21,
    color: '#000000',
  },
  seeAllButton: {
    paddingVertical: 2,
  },
  seeAllText: {
    fontFamily: 'DMSans_400Regular',
    fontSize: 14,
    lineHeight: 18,
    color: '#000000',
  },
  recentList: {
    paddingHorizontal: 20,
    gap: 10,
    marginBottom: 20,
  },
  recentItemCard: {
    backgroundColor: '#FFFFFF',
    borderWidth: 1.5,
    borderColor: '#EBEBEB',
    borderRadius: 14,
    padding: 14,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 18,
    height: 78,
  },
  recentItemThumb: {
    width: 50,
    height: 50,
    borderRadius: 10,
  },
  recentItemMiddle: {
    flex: 1,
    gap: 6,
  },
  recentItemTitle: {
    fontFamily: 'DMSans_400Regular',
    fontSize: 14,
    lineHeight: 18,
    color: '#000000',
  },
  recentItemSub: {
    fontFamily: 'DMSans_400Regular',
    fontSize: 14,
    lineHeight: 18,
    color: '#898989',
  },
  progressBarBg: {
    height: 3,
    backgroundColor: '#D9D9D9',
    borderRadius: 50,
    width: 170,
  },
  progressBarFill: {
    height: '100%',
    backgroundColor: '#4CAF50',
    borderRadius: 50,
  },
  recentItemRight: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  recentItemValue: {
    fontFamily: 'DMSans_400Regular',
    fontSize: 14,
    lineHeight: 18,
    color: '#000000',
    marginLeft: 2,
  },
  downloadButton: {
    marginHorizontal: 20,
    backgroundColor: '#4CAF50',
    borderRadius: 14,
    paddingVertical: 14,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 2,
    marginBottom: 30,
    ...Platform.select({
      ios: {
        shadowColor: '#4CAF50',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.12,
        shadowRadius: 4,
      },
      android: {
        elevation: 3,
      },
      web: {
        boxShadow: '0px 2px 4px rgba(76, 175, 80, 0.12)',
      }
    }),
  },
  downloadText: {
    fontFamily: 'DMSans_500Medium',
    fontSize: 15,
    lineHeight: 20,
    color: '#FFFFFF',
  },
  downloadSubtext: {
    fontFamily: 'DMSans_400Regular',
    fontSize: 14,
    lineHeight: 18,
    color: '#F0F0F0',
  },
  modalBackdropContainer: {
    position: 'absolute',
    left: 0,
    right: 0,
    top: 0,
    bottom: 0,
    zIndex: 9999,
  },
  modalBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.4)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalContent: {
    width: 376.5,
    height: 572,
    padding: 25,
    backgroundColor: '#FFFFFF',
    borderWidth: 1.5,
    borderColor: '#EBEBEB',
    borderRadius: 14,
    gap: 12,
    justifyContent: 'space-between',
  },
  modalTitle: {
    fontFamily: 'Poppins_500Medium',
    fontSize: 16,
    lineHeight: 24,
    color: '#000000',
  },
  modalScroll: {
    flex: 1,
    gap: 20,
    marginVertical: 10,
  },
  filterSectionCard: {
    padding: 16,
    backgroundColor: '#FFFFFF',
    borderWidth: 1.5,
    borderColor: '#EBEBEB',
    borderRadius: 14,
    gap: 12,
    height: 199,
    width: 326.5,
  },
  filterSectionTitle: {
    fontFamily: 'DMSans_400Regular',
    fontSize: 16,
    lineHeight: 21,
    color: '#000000',
  },
  gridContainerModal: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    columnGap: 11,
    rowGap: 10,
    width: '100%',
  },
  gridItem: {
    width: 65.38,
    height: 38,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#EBEBEB',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
  },
  gridItemActive: {
    backgroundColor: '#4CAF50',
    borderColor: '#4CAF50',
  },
  gridItemText: {
    fontFamily: 'DMSans_400Regular',
    fontSize: 14,
    lineHeight: 18,
    color: '#000000',
    textAlign: 'center',
  },
  gridItemTextActive: {
    color: '#FFFFFF',
  },
  modalApplyButton: {
    width: 326,
    height: 48,
    backgroundColor: '#4CAF50',
    borderRadius: 14,
    justifyContent: 'center',
    alignItems: 'center',
    ...Platform.select({
      ios: {
        shadowColor: '#4CAF50',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.12,
        shadowRadius: 4,
      },
      android: {
        elevation: 2,
      },
      web: {
        boxShadow: '0px 2px 4px rgba(76, 175, 80, 0.12)',
      }
    }),
  },
  modalApplyButtonText: {
    fontFamily: 'DMSans_500Medium',
    fontSize: 15,
    lineHeight: 20,
    color: '#FFFFFF',
    textAlign: 'center',
  },
});
