import { StyleSheet, Platform } from 'react-native';
import { s, vs, ms } from '@/utils/scale';

export const styles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: '#FAFAF9',
  },
  scrollContent: {
    paddingBottom: vs(120), // space for bottom download button + navbar
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: s(20),
    marginTop: Platform.OS === 'ios' ? vs(50) : vs(30),
    marginBottom: vs(20),
  },
  headerLeft: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    gap: s(12),
    marginRight: s(10),
  },
  backButton: {
    width: s(48),
    height: s(48),
    borderRadius: s(15),
    backgroundColor: '#4CAF50',
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerTitle: {
    flex: 1,
    fontFamily: 'Poppins_500Medium',
    fontSize: ms(18),
    lineHeight: ms(27),
    color: '#000000',
  },
  filterButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: vs(10),
    paddingHorizontal: s(12),
    gap: s(6),
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#4CAF50',
    borderRadius: s(10),
    maxWidth: s(130),
  },
  filterText: {
    fontFamily: 'DMSans_400Regular',
    fontSize: ms(12),
    lineHeight: ms(16),
    color: '#000000',
  },
  gridContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    paddingHorizontal: s(20),
    gap: s(12),
    marginBottom: vs(20),
  },
  card: {
    width: '48%', // dynamic width for 2-column grid
    flexGrow: 1,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#4CAF50',
    borderRadius: s(10),
    padding: s(12),
    gap: vs(10),
  },
  cardIconBox: {
    width: s(36),
    height: s(36),
    borderRadius: s(8),
    backgroundColor: 'rgba(76, 175, 80, 0.2)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  cardIcon: {
    width: s(20),
    height: s(20),
  },
  cardLabel: {
    fontFamily: 'DMSans_400Regular',
    fontSize: ms(14),
    lineHeight: ms(20),
    color: '#898989',
  },
  cardValueContainer: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  cardValue: {
    fontFamily: 'DMSans_500Medium',
    fontSize: ms(16),
    lineHeight: ms(22),
    color: '#000000',
    marginLeft: s(2),
  },
  cardTrendRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: s(4),
  },
  cardTrendText: {
    fontFamily: 'DMSans_400Regular',
    fontSize: ms(12),
    lineHeight: ms(16),
    color: '#4CAF50',
  },
  cardSubtext: {
    fontFamily: 'DMSans_400Regular',
    fontSize: ms(12),
    lineHeight: ms(16),
    color: '#898989',
  },
  chartCard: {
    marginHorizontal: s(20),
    backgroundColor: '#FFFFFF',
    borderWidth: 1.5,
    borderColor: '#EBEBEB',
    borderRadius: s(14),
    padding: s(16),
    gap: vs(12),
    marginBottom: vs(20),
  },
  chartTitle: {
    fontFamily: 'DMSans_500Medium',
    fontSize: ms(16),
    lineHeight: ms(21),
    color: '#000000',
  },
  chartWrapper: {
    height: vs(210),
    flexDirection: 'row',
  },
  yAxis: {
    width: s(40),
    height: vs(160),
    justifyContent: 'space-between',
    alignItems: 'flex-start',
  },
  yAxisLabelContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    height: vs(16),
  },
  yAxisText: {
    fontFamily: 'DMSans_400Regular',
    fontSize: ms(12),
    lineHeight: ms(16),
    color: '#898989',
    marginLeft: s(2),
  },
  chartPlotArea: {
    flex: 1,
    position: 'relative',
    height: vs(160),
  },
  gridLinesContainer: {
    position: 'absolute',
    left: 0,
    right: 0,
    top: 0,
    bottom: 0,
    justifyContent: 'space-between',
  },
  gridLine: {
    height: 1,
    backgroundColor: '#EBEBEB',
    width: '100%',
  },
  barsContainer: {
    position: 'absolute',
    left: 0,
    right: 0,
    top: 0,
    bottom: 0,
    flexDirection: 'row',
    justifyContent: 'space-around',
    alignItems: 'flex-end',
    paddingHorizontal: s(10),
  },
  barCol: {
    alignItems: 'center',
    justifyContent: 'flex-end',
    height: '100%',
  },
  barVal: {
    fontFamily: 'DMSans_400Regular',
    fontSize: ms(12),
    lineHeight: ms(16),
    color: '#000000',
    marginBottom: vs(4),
  },
  bar: {
    width: s(25),
    backgroundColor: 'rgba(76, 175, 80, 0.8)',
    borderTopLeftRadius: s(5),
    borderTopRightRadius: s(5),
  },
  xAxis: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    paddingLeft: s(40), // align with bars container
    marginTop: vs(10),
  },
  xAxisText: {
    fontFamily: 'DMSans_400Regular',
    fontSize: ms(12),
    lineHeight: ms(16),
    color: '#898989',
    width: s(60),
    textAlign: 'center',
  },
  sectionTitle: {
    fontFamily: 'DMSans_500Medium',
    fontSize: ms(16),
    lineHeight: ms(21),
    color: '#000000',
    marginHorizontal: s(20),
    marginBottom: vs(12),
  },
  topCropCard: {
    marginHorizontal: s(20),
    flexDirection: 'row',
    alignItems: 'center',
    padding: s(14),
    backgroundColor: '#FFFFFF',
    borderWidth: 1.5,
    borderColor: '#EBEBEB',
    borderRadius: s(14),
    gap: s(12),
    marginBottom: vs(20),
  },
  topCropImage: {
    width: s(120),
    height: s(120),
    borderRadius: s(20),
  },
  topCropDetails: {
    flex: 1,
    gap: vs(6),
  },
  topCropTitle: {
    fontFamily: 'DMSans_400Regular',
    fontSize: ms(14),
    lineHeight: ms(18),
    color: '#000000',
  },
  topCropRow: {
    flexDirection: 'column',
    gap: vs(2),
  },
  topCropLabel: {
    fontFamily: 'DMSans_400Regular',
    fontSize: ms(14),
    lineHeight: ms(18),
    color: '#898989',
  },
  topCropValue: {
    fontFamily: 'DMSans_400Regular',
    fontSize: ms(14),
    lineHeight: ms(18),
    color: '#000000',
  },
  topCropRevenueContainer: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  topCropRevenueValue: {
    fontFamily: 'DMSans_500Medium',
    fontSize: ms(14),
    lineHeight: ms(18),
    color: '#4CAF50',
    marginLeft: s(2),
  },
  recentHeaderRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginHorizontal: s(20),
    marginBottom: vs(12),
  },
  recentTitle: {
    fontFamily: 'DMSans_500Medium',
    fontSize: ms(16),
    lineHeight: ms(21),
    color: '#000000',
  },
  seeAllButton: {
    paddingVertical: vs(2),
  },
  seeAllText: {
    fontFamily: 'DMSans_400Regular',
    fontSize: ms(14),
    lineHeight: ms(18),
    color: '#000000',
  },
  recentList: {
    paddingHorizontal: s(20),
    gap: vs(10),
    marginBottom: vs(20),
  },
  recentItemCard: {
    backgroundColor: '#FFFFFF',
    borderWidth: 1.5,
    borderColor: '#EBEBEB',
    borderRadius: s(14),
    padding: s(14),
    flexDirection: 'row',
    alignItems: 'center',
    gap: s(18),
    height: vs(78),
  },
  recentItemThumb: {
    width: s(50),
    height: s(50),
    borderRadius: s(10),
  },
  recentItemMiddle: {
    flex: 1,
    gap: vs(6),
  },
  recentItemTitle: {
    fontFamily: 'DMSans_400Regular',
    fontSize: ms(14),
    lineHeight: ms(18),
    color: '#000000',
  },
  recentItemSub: {
    fontFamily: 'DMSans_400Regular',
    fontSize: ms(14),
    lineHeight: ms(18),
    color: '#898989',
  },
  progressBarBg: {
    height: vs(3),
    backgroundColor: '#D9D9D9',
    borderRadius: 50,
    width: '100%',
  },
  progressBarFill: {
    height: '100%',
    backgroundColor: '#4CAF50',
    borderRadius: 50,
  },
  recentItemRight: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  recentItemValue: {
    fontFamily: 'DMSans_400Regular',
    fontSize: ms(14),
    lineHeight: ms(18),
    color: '#000000',
    marginLeft: s(2),
  },
  downloadButton: {
    marginHorizontal: s(20),
    backgroundColor: '#4CAF50',
    borderRadius: s(14),
    paddingVertical: vs(14),
    alignItems: 'center',
    justifyContent: 'center',
    gap: vs(2),
    marginBottom: vs(30),
    ...Platform.select({
      ios: {
        shadowColor: '#4CAF50',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.12,
        shadowRadius: 4,
      },
      android: {
        elevation: 3,
      },
      web: {
        boxShadow: '0px 2px 4px rgba(76, 175, 80, 0.12)',
      }
    }),
  },
  downloadText: {
    fontFamily: 'DMSans_500Medium',
    fontSize: ms(15),
    lineHeight: ms(20),
    color: '#FFFFFF',
  },
  downloadSubtext: {
    fontFamily: 'DMSans_400Regular',
    fontSize: ms(14),
    lineHeight: ms(18),
    color: '#F0F0F0',
  },
  modalBackdropContainer: {
    position: 'absolute',
    left: 0,
    right: 0,
    top: 0,
    bottom: 0,
    zIndex: 9999,
  },
  modalBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.4)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalContent: {
    width: '90%',
    maxWidth: s(400),
    padding: s(25),
    backgroundColor: '#FFFFFF',
    borderWidth: 1.5,
    borderColor: '#EBEBEB',
    borderRadius: s(14),
    gap: vs(12),
  },
  modalTitle: {
    fontFamily: 'Poppins_500Medium',
    fontSize: ms(16),
    lineHeight: ms(24),
    color: '#000000',
  },
  modalScroll: {
    gap: vs(20),
  },
  filterSectionCard: {
    padding: s(16),
    backgroundColor: '#FFFFFF',
    borderWidth: 1.5,
    borderColor: '#EBEBEB',
    borderRadius: s(14),
    gap: vs(12),
    height: vs(199),
    width: '100%',
  },
  filterSectionTitle: {
    fontFamily: 'DMSans_400Regular',
    fontSize: ms(16),
    lineHeight: ms(21),
    color: '#000000',
  },
  gridContainerModal: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    rowGap: vs(10),
    width: '100%',
  },
  gridItem: {
    width: '23%',
    height: vs(38),
    borderRadius: s(10),
    borderWidth: 1,
    borderColor: '#EBEBEB',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
  },
  gridItemActive: {
    backgroundColor: '#4CAF50',
    borderColor: '#4CAF50',
  },
  gridItemText: {
    fontFamily: 'DMSans_400Regular',
    fontSize: ms(14),
    lineHeight: ms(18),
    color: '#000000',
    textAlign: 'center',
  },
  gridItemTextActive: {
    color: '#FFFFFF',
  },
  modalApplyButton: {
    width: '100%',
    height: vs(48),
    backgroundColor: '#4CAF50',
    borderRadius: s(14),
    justifyContent: 'center',
    alignItems: 'center',
    ...Platform.select({
      ios: {
        shadowColor: '#4CAF50',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.12,
        shadowRadius: 4,
      },
      android: {
        elevation: 2,
      },
      web: {
        boxShadow: '0px 2px 4px rgba(76, 175, 80, 0.12)',
      }
    }),
  },
  modalApplyButtonText: {
    fontFamily: 'DMSans_500Medium',
    fontSize: ms(15),
    lineHeight: ms(20),
    color: '#FFFFFF',
    textAlign: 'center',
  },
});
