import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  root: {
    flex: 1,
    backgroundColor: '#FAFAF9',
  },
  keyboardView: {
    flex: 1,
  },
  scrollContent: {
    flexGrow: 1,
    alignItems: 'center',
    backgroundColor: '#FAFAF9',
  },
  canvas: {
    width: '100%',
    minHeight: '100%',
    backgroundColor: '#FAFAF9',
    position: 'relative',
  },
  screen: {
    flex: 1,
    paddingHorizontal: 20,
    paddingTop: 30,
    paddingBottom: 120, // Space for footer
  },
  headerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 20,
    gap: 15,
  },
  backButton: {
    width: 48,
    height: 48,
    borderRadius: 15,
    backgroundColor: '#4CAF50',
    alignItems: 'center',
    justifyContent: 'center',
  },
  titleWrapper: {
    justifyContent: 'center',
  },
  title: {
    fontFamily: 'Poppins_500Medium',
    fontSize: 18,
    lineHeight: 27,
    color: '#000000',
  },
  subtitle: {
    fontFamily: 'DMSans_400Regular',
    fontSize: 16,
    lineHeight: 21,
    color: '#000000',
  },
  progressRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 30,
    gap: 6,
  },
  progressSegment: {
    flex: 1,
    height: 5,
    borderRadius: 15,
    backgroundColor: '#EBEBEB',
  },
  progressSegmentActive: {
    backgroundColor: '#4CAF50',
  },
  formStack: {
    gap: 12,
  },
  row: {
    flexDirection: 'row',
    gap: 22,
  },
  inputGroup: {
    flex: 1,
    backgroundColor: '#FFFFFF',
    borderWidth: 1.5,
    borderColor: '#EBEBEB',
    borderRadius: 14,
    paddingTop: 15,
    paddingBottom: 15,
    paddingHorizontal: 16,
    gap: 4,
    justifyContent: 'center',
  },
  inputGroupRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  inputLabel: {
    fontFamily: 'DMSans_400Regular',
    fontSize: 14,
    lineHeight: 18,
    color: '#6D6D6D',
  },
  input: {
    fontFamily: 'DMSans_400Regular',
    fontSize: 16,
    lineHeight: 21,
    color: '#000000',
    padding: 0,
    margin: 0,
    outlineWidth: 0,
  },
  inputRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  rupeeSymbol: {
    fontFamily: 'DMSans_400Regular',
    fontSize: 16,
    lineHeight: 21,
    color: '#000000',
    marginRight: 4,
  },
  banner: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#436EEE',
    borderRadius: 12,
    paddingVertical: 10,
    paddingHorizontal: 12,
    gap: 8,
    marginTop: 8,
  },
  bannerText: {
    fontFamily: 'Outfit_400Regular',
    fontSize: 14,
    lineHeight: 18,
    color: '#FFFFFF',
    flex: 1,
  },
  footer: {
    position: 'absolute',
    bottom: 50,
    left: 20,
    right: 20,
  },
  primaryButton: {
    height: 50,
    backgroundColor: '#4CAF50',
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#4CAF50',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.12,
    shadowRadius: 4,
    elevation: 2,
  },
  primaryButtonText: {
    fontFamily: 'DMSans_500Medium',
    fontSize: 15,
    lineHeight: 20,
    color: '#FFFFFF',
  },
  uploadBox: {
    borderWidth: 1,
    borderColor: '#EBEBEB',
    borderStyle: 'dashed',
    borderRadius: 14,
    padding: 30,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 20,
    height: 200,
    backgroundColor: '#FFFFFF',
  },
  uploadTitle: {
    fontFamily: 'Poppins_600SemiBold',
    fontSize: 16,
    color: '#1a1a1a',
    marginTop: 10,
    textAlign: 'center',
  },
  uploadSubtitle: {
    fontFamily: 'DMSans_400Regular',
    fontSize: 14,
    color: '#888888',
    textAlign: 'center',
  },
  photoCount: {
    fontFamily: 'DMSans_500Medium',
    fontSize: 16,
    color: '#1a1a1a',
    marginBottom: 12,
  },
  photoGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
  },
  photoWrapper: {
    width: '30%',
    aspectRatio: 1,
    borderRadius: 12,
    overflow: 'hidden',
    position: 'relative',
  },
  photo: {
    width: '100%',
    height: '100%',
  },
  addMoreBox: {
    width: '30%',
    aspectRatio: 1,
    borderRadius: 12,
    backgroundColor: '#F3F3F3',
    alignItems: 'center',
    justifyContent: 'center',
  },
  dropdownContainer: {
    position: 'absolute',
    top: 72,
    left: 0,
    right: 0,
    backgroundColor: '#FFFFFF',
    borderRadius: 14,
    borderWidth: 1.5,
    borderColor: '#EBEBEB',
    zIndex: 100,
    elevation: 5,
    overflow: 'hidden',
  },
  inlineDropdownContainer: {
    backgroundColor: '#FFFFFF',
    borderRadius: 14,
    borderWidth: 1.5,
    borderColor: '#EBEBEB',
    overflow: 'hidden',
    marginTop: 8,
  },
  dropdownItem: {
    paddingVertical: 12,
    paddingHorizontal: 16,
  },
  dropdownItemActive: {
    backgroundColor: '#EEEEEE',
  },
  dropdownText: {
    fontFamily: 'DMSans_400Regular',
    fontSize: 14,
    color: '#000000',
  },
});
