import { StyleSheet } from 'react-native';
import { s, vs, ms } from '@/utils/scale';

export const styles = StyleSheet.create({
  root: {
    flex: 1,
    backgroundColor: '#FAFAF9',
  },
  keyboardView: {
    flex: 1,
  },
  scrollContent: {
    flexGrow: 1,
    alignItems: 'center',
    backgroundColor: '#FAFAF9',
  },
  canvas: {
    width: '100%',
    minHeight: '100%',
    backgroundColor: '#FAFAF9',
    position: 'relative',
  },
  screen: {
    flex: 1,
    paddingHorizontal: s(20),
    paddingTop: vs(30),
    paddingBottom: vs(120), // Space for footer
  },
  headerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: vs(20),
    gap: s(15),
  },
  backButton: {
    width: s(48),
    height: s(48),
    borderRadius: s(15),
    backgroundColor: '#4CAF50',
    alignItems: 'center',
    justifyContent: 'center',
  },
  titleWrapper: {
    justifyContent: 'center',
  },
  title: {
    fontFamily: 'Poppins_500Medium',
    fontSize: ms(18),
    lineHeight: ms(27),
    color: '#000000',
  },
  subtitle: {
    fontFamily: 'DMSans_400Regular',
    fontSize: ms(16),
    lineHeight: ms(21),
    color: '#000000',
  },
  progressRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: vs(30),
    gap: s(6),
  },
  progressSegment: {
    flex: 1,
    height: vs(5),
    borderRadius: s(15),
    backgroundColor: '#EBEBEB',
  },
  progressSegmentActive: {
    backgroundColor: '#4CAF50',
  },
  formStack: {
    gap: vs(12),
  },
  row: {
    flexDirection: 'row',
    gap: s(22),
  },
  inputGroup: {
    flex: 1,
    backgroundColor: '#FFFFFF',
    borderWidth: 1.5,
    borderColor: '#EBEBEB',
    borderRadius: s(14),
    paddingTop: vs(15),
    paddingBottom: vs(15),
    paddingHorizontal: s(16),
    gap: vs(4),
    justifyContent: 'center',
  },
  inputGroupRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  inputLabel: {
    fontFamily: 'DMSans_400Regular',
    fontSize: ms(14),
    lineHeight: ms(18),
    color: '#6D6D6D',
  },
  input: {
    fontFamily: 'DMSans_400Regular',
    fontSize: ms(16),
    lineHeight: ms(21),
    color: '#000000',
    padding: 0,
    margin: 0,
    outlineWidth: 0,
  },
  inputRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  rupeeSymbol: {
    fontFamily: 'DMSans_400Regular',
    fontSize: ms(16),
    lineHeight: ms(21),
    color: '#000000',
    marginRight: s(4),
  },
  banner: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#436EEE',
    borderRadius: s(12),
    paddingVertical: vs(10),
    paddingHorizontal: s(12),
    gap: s(8),
    marginTop: vs(8),
  },
  bannerText: {
    fontFamily: 'Outfit_400Regular',
    fontSize: ms(14),
    lineHeight: ms(18),
    color: '#FFFFFF',
    flex: 1,
  },
  footer: {
    position: 'absolute',
    bottom: vs(50),
    left: s(20),
    right: s(20),
  },
  primaryButton: {
    height: vs(50),
    backgroundColor: '#4CAF50',
    borderRadius: s(14),
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#4CAF50',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.12,
    shadowRadius: 4,
    elevation: 2,
  },
  primaryButtonText: {
    fontFamily: 'DMSans_500Medium',
    fontSize: ms(15),
    lineHeight: ms(20),
    color: '#FFFFFF',
  },
  uploadBox: {
    borderWidth: 1,
    borderColor: '#EBEBEB',
    borderStyle: 'dashed',
    borderRadius: s(14),
    padding: s(30),
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: vs(20),
    height: vs(200),
    backgroundColor: '#FFFFFF',
  },
  uploadTitle: {
    fontFamily: 'Poppins_600SemiBold',
    fontSize: ms(16),
    color: '#1a1a1a',
    marginTop: vs(10),
    textAlign: 'center',
  },
  uploadSubtitle: {
    fontFamily: 'DMSans_400Regular',
    fontSize: ms(14),
    color: '#888888',
    textAlign: 'center',
  },
  photoCount: {
    fontFamily: 'DMSans_500Medium',
    fontSize: ms(16),
    color: '#1a1a1a',
    marginBottom: vs(12),
  },
  photoGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: s(12),
  },
  photoWrapper: {
    width: '30%',
    aspectRatio: 1,
    borderRadius: s(12),
    overflow: 'hidden',
    position: 'relative',
  },
  photo: {
    width: '100%',
    height: '100%',
  },
  addMoreBox: {
    width: '30%',
    aspectRatio: 1,
    borderRadius: s(12),
    backgroundColor: '#F3F3F3',
    alignItems: 'center',
    justifyContent: 'center',
  },
  dropdownContainer: {
    position: 'absolute',
    top: vs(72),
    left: 0,
    right: 0,
    backgroundColor: '#FFFFFF',
    borderRadius: s(14),
    borderWidth: 1.5,
    borderColor: '#EBEBEB',
    zIndex: 100,
    elevation: 5,
    overflow: 'hidden',
  },
  inlineDropdownContainer: {
    backgroundColor: '#FFFFFF',
    borderRadius: s(14),
    borderWidth: 1.5,
    borderColor: '#EBEBEB',
    overflow: 'hidden',
    marginTop: vs(8),
  },
  dropdownItem: {
    paddingVertical: vs(12),
    paddingHorizontal: s(16),
  },
  dropdownItemActive: {
    backgroundColor: '#EEEEEE',
  },
  dropdownText: {
    fontFamily: 'DMSans_400Regular',
    fontSize: ms(14),
    color: '#000000',
  },
});
