import { StyleSheet } from 'react-native';
import { s, vs, ms } from '@/utils/scale';

export const styles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: '#FAFAF9',
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: s(20),
    marginTop: vs(30),
    marginBottom: vs(20),
  },
  backButton: {
    width: s(48),
    height: s(48),
    borderRadius: s(15),
    backgroundColor: '#4CAF50',
    alignItems: 'center',
    justifyContent: 'center',
  },
  statusPill: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: s(12),
    paddingVertical: vs(6),
    borderWidth: 1,
    borderColor: '#4CAF50',
    borderRadius: s(14),
  },
  statusText: {
    fontFamily: 'DMSans_400Regular',
    fontSize: ms(16),
    color: '#4CAF50',
  },
  content: {
    paddingHorizontal: s(20),
    paddingBottom: vs(100),
  },
  mainImage: {
    width: '100%',
    height: vs(250),
    borderRadius: s(14),
    marginBottom: vs(20),
  },
  titleCard: {
    backgroundColor: '#FFFFFF',
    borderWidth: 1.5,
    borderColor: '#EBEBEB',
    borderRadius: s(14),
    paddingVertical: vs(15),
    paddingHorizontal: s(10),
    alignItems: 'center',
    marginBottom: vs(20),
  },
  titleText: {
    fontFamily: 'DMSans_500Medium',
    fontSize: ms(18),
    lineHeight: ms(23),
    color: '#000000',
    marginBottom: vs(5),
  },
  subtitleText: {
    fontFamily: 'DMSans_400Regular',
    fontSize: ms(16),
    color: '#6D6D6D',
  },
  statsCard: {
    flexDirection: 'row',
    backgroundColor: '#FFFFFF',
    borderWidth: 1.5,
    borderColor: '#EBEBEB',
    borderRadius: s(14),
    paddingVertical: vs(15),
    alignItems: 'center',
    justifyContent: 'space-evenly',
    marginBottom: vs(20),
  },
  statCol: {
    alignItems: 'center',
    justifyContent: 'center',
    flex: 1,
  },
  statValueRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  rupeeBadgeSmall: {
    width: s(18),
    height: s(18),
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: s(4),
  },
  statValueSmall: {
    fontFamily: 'DMSans_600SemiBold',
    fontSize: ms(14),
    color: '#000000',
    marginRight: s(2),
  },
  statValue: {
    fontFamily: 'DMSans_600SemiBold',
    fontSize: ms(18),
    color: '#000000',
  },
  statLabel: {
    fontFamily: 'DMSans_400Regular',
    fontSize: ms(14),
    color: '#6D6D6D',
    marginTop: vs(2),
  },
  divider: {
    width: 1,
    height: vs(40),
    backgroundColor: '#EBEBEB',
  },
  detailsCard: {
    backgroundColor: '#FFFFFF',
    borderWidth: 1.5,
    borderColor: '#EBEBEB',
    borderRadius: s(14),
    padding: s(14),
    marginBottom: vs(20),
  },
  detailsSection: {
    backgroundColor: '#FFFFFF',
    borderWidth: 1.5,
    borderColor: '#EBEBEB',
    borderRadius: s(14),
    padding: s(15),
    marginBottom: vs(10),
    gap: vs(10),
  },
  detailRow: {
    flexDirection: 'row',
  },
  detailLabel: {
    fontFamily: 'DMSans_400Regular',
    fontSize: ms(16),
    color: '#6D6D6D',
    width: s(110),
  },
  detailValue: {
    fontFamily: 'DMSans_400Regular',
    fontSize: ms(16),
    color: '#000000',
    flex: 1,
  },
  totalSection: {
    backgroundColor: '#FFFFFF',
    borderWidth: 1.5,
    borderColor: '#EBEBEB',
    borderRadius: s(14),
    padding: s(15),
    flexDirection: 'row',
    alignItems: 'center',
  },
  totalLabel: {
    fontFamily: 'DMSans_400Regular',
    fontSize: ms(18),
    color: '#6D6D6D',
    marginRight: s(10),
  },
  totalValue: {
    fontFamily: 'DMSans_400Regular',
    fontSize: ms(18),
    color: '#000000',
  },
  actionButtons: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: s(20),
    paddingBottom: vs(40),
    gap: s(15),
  },
  deleteButton: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#E62326',
    borderRadius: s(14),
    paddingVertical: vs(14),
    gap: s(8),
    shadowColor: 'rgba(230, 35, 38, 0.12)',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 1,
    shadowRadius: 4,
    elevation: 4,
  },
  editButton: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#4CAF50',
    borderRadius: s(14),
    paddingVertical: vs(14),
    gap: s(8),
    shadowColor: 'rgba(76, 175, 80, 0.12)',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 1,
    shadowRadius: 4,
    elevation: 4,
  },
  actionButtonText: {
    fontFamily: 'DMSans_400Regular',
    fontSize: ms(15),
    color: '#FFFFFF',
  }
});
