import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: '#FAFAF9',
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    marginTop: 30,
    marginBottom: 20,
  },
  backButton: {
    width: 48,
    height: 48,
    borderRadius: 15,
    backgroundColor: '#4CAF50',
    alignItems: 'center',
    justifyContent: 'center',
  },
  statusPill: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderWidth: 1,
    borderColor: '#4CAF50',
    borderRadius: 14,
  },
  statusText: {
    fontFamily: 'DMSans_400Regular',
    fontSize: 16,
    color: '#4CAF50',
  },
  content: {
    paddingHorizontal: 20,
    paddingBottom: 100,
  },
  mainImage: {
    width: '100%',
    height: 250,
    borderRadius: 14,
    marginBottom: 20,
  },
  titleCard: {
    backgroundColor: '#FFFFFF',
    borderWidth: 1.5,
    borderColor: '#EBEBEB',
    borderRadius: 14,
    paddingVertical: 15,
    paddingHorizontal: 10,
    alignItems: 'center',
    marginBottom: 20,
  },
  titleText: {
    fontFamily: 'DMSans_500Medium',
    fontSize: 18,
    lineHeight: 23,
    color: '#000000',
    marginBottom: 5,
  },
  subtitleText: {
    fontFamily: 'DMSans_400Regular',
    fontSize: 16,
    color: '#6D6D6D',
  },
  statsCard: {
    flexDirection: 'row',
    backgroundColor: '#FFFFFF',
    borderWidth: 1.5,
    borderColor: '#EBEBEB',
    borderRadius: 14,
    paddingVertical: 15,
    alignItems: 'center',
    justifyContent: 'space-evenly',
    marginBottom: 20,
  },
  statCol: {
    alignItems: 'center',
    justifyContent: 'center',
    flex: 1,
  },
  statValueRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  rupeeBadgeSmall: {
    width: 18,
    height: 18,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 4,
  },
  statValueSmall: {
    fontFamily: 'DMSans_600SemiBold',
    fontSize: 14,
    color: '#000000',
    marginRight: 2,
  },
  statValue: {
    fontFamily: 'DMSans_600SemiBold',
    fontSize: 18,
    color: '#000000',
  },
  statLabel: {
    fontFamily: 'DMSans_400Regular',
    fontSize: 14,
    color: '#6D6D6D',
    marginTop: 2,
  },
  divider: {
    width: 1,
    height: 40,
    backgroundColor: '#EBEBEB',
  },
  detailsCard: {
    backgroundColor: '#FFFFFF',
    borderWidth: 1.5,
    borderColor: '#EBEBEB',
    borderRadius: 14,
    padding: 14,
    marginBottom: 20,
  },
  detailsSection: {
    backgroundColor: '#FFFFFF',
    borderWidth: 1.5,
    borderColor: '#EBEBEB',
    borderRadius: 14,
    padding: 15,
    marginBottom: 10,
    gap: 10,
  },
  detailRow: {
    flexDirection: 'row',
  },
  detailLabel: {
    fontFamily: 'DMSans_400Regular',
    fontSize: 16,
    color: '#6D6D6D',
    width: 110,
  },
  detailValue: {
    fontFamily: 'DMSans_400Regular',
    fontSize: 16,
    color: '#000000',
    flex: 1,
  },
  totalSection: {
    backgroundColor: '#FFFFFF',
    borderWidth: 1.5,
    borderColor: '#EBEBEB',
    borderRadius: 14,
    padding: 15,
    flexDirection: 'row',
    alignItems: 'center',
  },
  totalLabel: {
    fontFamily: 'DMSans_400Regular',
    fontSize: 18,
    color: '#6D6D6D',
    marginRight: 10,
  },
  totalValue: {
    fontFamily: 'DMSans_400Regular',
    fontSize: 18,
    color: '#000000',
  },
  actionButtons: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    paddingBottom: 40,
    gap: 15,
  },
  deleteButton: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#E62326',
    borderRadius: 14,
    paddingVertical: 14,
    gap: 8,
    shadowColor: 'rgba(230, 35, 38, 0.12)',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 1,
    shadowRadius: 4,
    elevation: 4,
  },
  editButton: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#4CAF50',
    borderRadius: 14,
    paddingVertical: 14,
    gap: 8,
    shadowColor: 'rgba(76, 175, 80, 0.12)',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 1,
    shadowRadius: 4,
    elevation: 4,
  },
  actionButtonText: {
    fontFamily: 'DMSans_400Regular',
    fontSize: 15,
    color: '#FFFFFF',
  }
});
